Threat Intel Feed Config Model
opensearch-project/security-analytics pull request #1028
Opened 2024-05-15 01:16 UTC by jowg-amazon

### Description
1. Refactors threat intel folder to include transport, resthandler, service, util, and model folders.
2. Adds the threat intel feed config model

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-20 17:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFConfig.java
> +public class SATIFConfig implements TIFConfig, Writeable, ScheduledJobParameter {
Javadocs

2024-05-20 18:08 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFConfig.java
> +    private Map<String, Object> iocMapStore;
This is the map that shows where we are storing the IOCs per feed. For opensearch it would be something like Map: Ip: <index name storing ip iocs>, DNS: <index name storing dns iocs>

2024-05-20 21:09 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFConfig.java
> +public class SATIFConfig implements TIFConfig, Writeable, ScheduledJobParameter {
added javadocs

2024-05-21 20:35 UTC, eirsep requested changes

2024-05-21 20:35 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFConfig.java
> + * Threat intel config interface
can we rename entity to TIFSource Config

2024-05-21 21:09 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFConfig.java
> + * Threat intel config interface
renamed to `TIFSourceConfig`

2024-05-22 00:25 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFConfig.java
> +    public static TIFJobState toState(String stateName) {
this is not scalable 

use `valueOf(String name)` which returns enum and wrap with try catch where catch returns null and logs error that couldnt parse enum

2024-05-22 00:29 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java
> +    private Boolean prepackaged;
let's have feed type instead of this

LICENSED
OPEN-SOURCED
CUSTOM
INTERNAL

2024-05-22 00:29 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFJobState.java
> +    DELETING,
REFRESHING?

2024-05-22 01:08 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/TIFJobState.java
> +    DELETING,
Added `REFRESHING` as a state

2024-05-22 01:08 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java
> +    private Boolean prepackaged;
added enum class for these fields

2024-05-22 01:09 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFConfig.java
> +    public static TIFJobState toState(String stateName) {
Changed it to use `valueOf`

2024-05-22 01:12 UTC, eirsep approved these changes

2024-05-22 01:31 UTC, sbcd90 approved these changes

2024-05-22 01:31 UTC, merged