Rough draft of IOC data model.
opensearch-project/security-analytics pull request #1029
Opened 2024-05-17 03:35 UTC by AWSHurneyt

### Description
These are the references I'm using.

**Domain documentation**
Section "6.4 Domain Name Object" of https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_k017w16zutw

**Hash documentation**
TBD - Still looking for a good reference for this

**IP documentation**
"6.8 IPv4 Address Object" section of https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_wh296fiwpklp
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-17 16:36 UTC, eirsep requested changes
can we add a validate function to verify feed id, values, type and value are non-null

2024-05-17 18:56 UTC, AWSHurneyt commented
> can we add a validate function to verify feed id, values, type and value are non-null

@eirsep Added some basic validation.

2024-05-20 23:14 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +import static org.opensearch.securityanalytics.model.Detector.NO_ID;
This references detector's No ID field, might be better to have IocDao's own field.

2024-05-20 23:14 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/model/IocDto.java
> +}
Does the DTO need a parse function?

2024-05-23 23:36 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +import static org.opensearch.securityanalytics.model.Detector.NO_ID;
Added a `NO_ID` variable in `IocDao`.

2024-05-23 23:36 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/IocDto.java
> +}
Added a `parse` function.

2024-05-24 23:10 UTC, eirsep reviewed
LGTM 
plz add serialization tests

2024-05-28 18:22 UTC, AWSHurneyt commented
> LGTM plz add serialization tests



> LGTM plz add serialization tests

@eirsep Added some unit tests. Will add more once we're more confident that this is the final structure of the data model.

2024-05-28 20:19 UTC, eirsep approved these changes

2024-05-28 20:19 UTC, merged