Create TIF Source Config API
opensearch-project/security-analytics pull request #1046
Opened 2024-05-24 00:53 UTC by jowg-amazon

### Description
Preliminary architecture and flow for creating a job index and indexing a source config object.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-24 00:58 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_CONFIG_URI = PLUGINS_BASE_URI + "/tif";
threat intel source?

2024-05-24 16:25 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_CONFIG_URI = PLUGINS_BASE_URI + "/tif";
updated to `/tif/source`

2024-05-24 23:15 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_BASE_URI = PLUGINS_BASE_URI + "/tif";
tif_source?

2024-05-24 23:16 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_SOURCE_CONFIG_URI = PLUGINS_BASE_URI + "/tif/source";
threat_intel/source?

2024-05-24 23:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    private SATIFSourceConfigDao satifSourceConfigDao;
SaTifSourceConfigDao*

2024-05-24 23:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                new RestIndexTIFConfigAction()
RestIndexTIFSourceConfigAction

2024-05-24 23:20 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                        log.warn("Unsupported document was indexed");
log level should be error
re-word message to make it more descriptive

message should include `job parser failed`, `$fieldName` (value), `in security analytics job registration`

2024-05-24 23:21 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                        return SATIFSourceConfig.parse(xcp, id, null);
why is the third param null

2024-05-24 23:22 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigAction.java
> + * Threat intel tif job creation action
more descriptive and talk about indexing config, downloading feed, setting up job scheduler job

2024-05-24 23:23 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigRequest.java
> +    private final WriteRequest.RefreshPolicy refreshPolicy;
dont accept param. always IMMEDIATE REFRESH

2024-05-24 23:24 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigResponse.java
> +    private final SATIFSourceConfigDto saTIFConfigDto;
if a word is an a acronym let's make it liek SaTifSourceConfigDto

2024-05-24 23:25 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                                     WriteRequest.RefreshPolicy refreshPolicy,
should always be refresh immediate. remove param

2024-05-24 23:25 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                                     final ActionListener<SATIFSourceConfig> actionListener) throws Exception {
throws Exception is not needed

2024-05-24 23:27 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                throw new SecurityAnalyticsException("Exception saving the tif source config in index", RestStatus.INTERNAL_SERVER_ERROR, e);
use listener.onFailure don't re-throw

2024-05-24 23:32 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +        IndexRequest indexRequest = new IndexRequest(SecurityAnalyticsPlugin.JOB_INDEX_NAME)
wrap entire logic in try-catch and listener.onFailure + log message in catch block

2024-05-24 23:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                log.debug("TIF source config indexed success.");
we need to log the document id.

2024-05-24 23:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                satifSourceConfig.setId(response.getId());
copy to new object.

2024-05-24 23:36 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +            throw new SecurityAnalyticsException("Runtime exception when getting the threat intel index mapping", RestStatus.INTERNAL_SERVER_ERROR, e);
Message can be "Failed to get threat intel index maping"

2024-05-25 05:21 UTC, eirsep requested changes

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_BASE_URI = PLUGINS_BASE_URI + "/tif";
changed to threat_intel

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TIF_SOURCE_CONFIG_URI = PLUGINS_BASE_URI + "/tif/source";
changed to threat_intel/source

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    private SATIFSourceConfigDao satifSourceConfigDao;
fixed

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                new RestIndexTIFConfigAction()
fixed

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                        log.warn("Unsupported document was indexed");
reworded error message

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigRequest.java
> +    private final WriteRequest.RefreshPolicy refreshPolicy;
removed param

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SAIndexTIFSourceConfigResponse.java
> +    private final SATIFSourceConfigDto saTIFConfigDto;
fixed

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                                     WriteRequest.RefreshPolicy refreshPolicy,
removed

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                                     final ActionListener<SATIFSourceConfig> actionListener) throws Exception {
removed

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +        IndexRequest indexRequest = new IndexRequest(SecurityAnalyticsPlugin.JOB_INDEX_NAME)
done

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +        client.index(indexRequest, new ActionListener<>() {
changed to ActionListener.wrap()

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                log.debug("TIF source config indexed success.");
logged id in message

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                throw new SecurityAnalyticsException("Exception saving the tif source config in index", RestStatus.INTERNAL_SERVER_ERROR, e);
done

2024-05-25 05:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +            throw new SecurityAnalyticsException("Runtime exception when getting the threat intel index mapping", RestStatus.INTERNAL_SERVER_ERROR, e);
Changed message

2024-05-25 05:23 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFSourceConfigDao.java
> +    IndexTIFSourceConfigResponse indexTIFConfig(IndexTIFSourceConfigRequest request, ActionListener <IndexTIFSourceConfigResponse> listener);
response would be at transport and rest layer?

2024-05-26 05:32 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
> +        SaTifSourceConfigDao.createJobIndexIfNotExists(createIndexStepListener);
this should be done in dao itself before create

2024-05-28 21:36 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +                log.error("Failed to create security analytics threat intel job index", e);
Changed to log the index name in error message

2024-05-28 21:36 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFSourceConfigDao.java
> +    IndexTIFSourceConfigResponse indexTIFConfig(IndexTIFSourceConfigRequest request, ActionListener <IndexTIFSourceConfigResponse> listener);
Renamed to TIFSourceConfigService and changed to abstract class, will follow up on implementation in future PR.

2024-05-28 21:37 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +                        return SATIFSourceConfig.parse(xcp, id, null);
Will address this in a future PR, need to understand what params should be used for parser

2024-05-28 23:59 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> -        SaTifSourceConfigDao = new SATIFSourceConfigDao(client, clusterService, threadPool);
what is this lock service??

2024-05-29 00:01 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/dao/SATIFSourceConfigDao.java
> +            lockService.releaseLock(lock);
what does this lockservice achieve??

2024-05-29 00:02 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/sacommons/TIFSourceConfigService.java
> +    IndexTIFSourceConfigResponse indexTIFConfig(IndexTIFSourceConfigRequest request, ActionListener <IndexTIFSourceConfigResponse> listener){
method should be abstract

2024-05-29 00:03 UTC, eirsep approved these changes
plz address comments in followup PR

2024-05-29 00:04 UTC, merged