Draft of IOC service
opensearch-project/security-analytics pull request #1048
Opened 2024-05-29 01:08 UTC by AWSHurneyt

### Description
Implemented draft of IocService.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-05-29 17:12 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    // TODO hurneyt IOC system index names should be refactored to include the timestamp instead of the IOC type
plz also incorporate feed id in index name

2024-05-29 17:13 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    // TODO hurneyt IOC system index names should be refactored to include the timestamp instead of the IOC type
Good callout, will do.

2024-05-29 18:38 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/services/IocServiceIT.java
> +public class IocServiceIT extends OpenSearchIntegTestCase {
thanks for adding integ tests for service! :D

2024-05-29 18:43 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> + * IOC Service implements operations that interact with retrieving IOCs from data sources,
can we have feed/iocs downloader seperate from the class that is indexing the iocs into system index.

2024-05-29 18:45 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +import java.util.Objects;
NIT: can we rename class to `Ioc`?  to keep consistence with model naming like Monitor.kt or Detector.java

2024-05-29 18:46 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +        return index.startsWith(IOC_INDEX_NAME_BASE) && this.clusterService.state().routingTable().hasIndex(index);
why do we have to do `index.startsWith(IOC_INDEX_NAME_BASE)` and why is method public?

2024-05-29 18:47 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +    public void initSystemIndexes(String index, ActionListener<FetchIocsActionResponse> listener) {
what is FetchIocsActionResponse? why is the invoker of init system indices method listening for FetchIocsActionResponse ?

2024-05-29 19:20 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
have to register batch size setting. let's give it a generic name. we can use it for all bulk requests

2024-05-29 19:20 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +                    if (Objects.equals(id, NO_ID)) {
why this check?

2024-05-29 19:21 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +                case ID_FIELD:
why are we allowing id to be empty or null at all?

2024-05-29 19:35 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +            initSystemIndexes(ioc.getType().getSystemIndexName(), listener);
why is init call inside for loop

2024-05-29 19:42 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +                    // TODO hurneyt finalize mappings once IOC data model PR is merged
PR is merged. you can add a mapping and we can iteratively make any edits to it as before we merge feature branch. let's get it in so we don't miss out

2024-05-29 19:43 UTC, eirsep requested changes

2024-05-29 19:43 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +        bulkRequest.setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE);
NIT: since we are batching bulk requests 
can you refresh only once after all bulk requests are submitted or on the last bulk request only

2024-05-29 19:47 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +            initSystemIndexes(ioc.getType().getSystemIndexName(), listener);
`ioc.getType().getSystemIndexName()`  -> this logic to derive system index name doesn't seem right

2024-05-29 23:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    // TODO hurneyt IOC system index names should be refactored to include the timestamp instead of the IOC type
true but the intersection of all feeds might give us some Ioc's which we can consider high serverity Iocs
the duplication would help us better with Ioc Insights and threat confidence of Iocs - number of feeds marking ioc as malicious

2024-05-29 23:55 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    // TODO hurneyt IOC system index names should be refactored to include the timestamp instead of the IOC type
No problem. Just wanted to confirm that was the intention.

@eirsep Also to clarify, by `feed id`, you're referring to the ID of the sourceConfig, correct? E.g., https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java#L67

2024-05-30 00:31 UTC, eirsep requested changes

2024-05-30 00:31 UTC, eirsep commented on build.gradle
> +        sa_commons_version = System.getProperty("sa_commons.version", opensearch_build)
Will not be opensearch based

2024-05-30 17:02 UTC, AWSHurneyt commented on build.gradle
> +        sa_commons_version = System.getProperty("sa_commons.version", opensearch_build)
Removed the build.gradle changes for now. Will add them in a separate PR.

2024-05-30 17:03 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +            initSystemIndexes(ioc.getType().getSystemIndexName(), listener);
This will be removed. I added this function when I was thinking of creating an index for each IOC type.

2024-05-30 22:24 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +import java.util.Objects;
Will revise.

2024-05-30 22:28 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +            initSystemIndexes(ioc.getType().getSystemIndexName(), listener);
The init function performs a check to see if the index exists, and then only creates the index if it doesn't. I initially performed the init check for each IOC because I was planning to store IOCs in type-specific indexes.

Since we're instead planning to store IOCs in feedSourceConfig-specific indexes; I've move the init call outside of the loop.

2024-05-30 22:41 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    // TODO hurneyt IOC system index names should be refactored to include the timestamp instead of the IOC type
> No problem. Just wanted to confirm that was the intention.
> 
> @eirsep Also to clarify, by `feed id`, you're referring to the ID of the sourceConfig, correct? E.g., https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/main/java/org/opensearch/securityanalytics/threatIntel/model/SATIFSourceConfig.java#L67

Confirmed offline that `feed id` refers to the sourceConfig ID.

2024-05-30 22:49 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +                case ID_FIELD:
My initial thought was that we needed to read the ID from the xcp; but I don't think that's needed anymore. Will remove.

2024-05-30 22:49 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/IocDao.java
> +                    if (Objects.equals(id, NO_ID)) {
My initial thought was that we needed to read the ID from the xcp; but I don't think that's needed anymore. Will remove.

2024-05-30 23:04 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +        return index.startsWith(IOC_INDEX_NAME_BASE) && this.clusterService.state().routingTable().hasIndex(index);
@eirsep I added the `startsWith` check just to confirm that the function is only being used to create indexes for the purposes of this feature. Do you think that check should be removed?

I implemented it as public just out of habit in case I might need it elsewhere; I'll change it to private.

2024-05-30 23:06 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +    public void initSystemIndexes(String index, ActionListener<FetchIocsActionResponse> listener) {
@eirsep The `FetchIocsActionResponse` is an artifact from when I was initially implementing this as a rest API. After discussing it with @jowg-amazon, she'll be passing the service an ActionListener, so I'll refactor this to a generic `ActionResponse` object for now and leave a TODO.

2024-05-30 23:08 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> +        bulkRequest.setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE);
Revised.

2024-05-30 23:16 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/IocService.java
> + * IOC Service implements operations that interact with retrieving IOCs from data sources,
Yes. Will separate the functions into another class in a separate PR.

2024-05-31 00:23 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
Clarified offline that using the existing batch setting on this line is sufficient for now.
https://github.com/opensearch-project/security-analytics/pull/1048/files#diff-9aa7b128ff9bc2c4d9f95581a20d89a90be23c1b9b9a4f29b7271daa5f826cd6R105

2024-06-05 19:37 UTC, eirsep commented on src/main/resources/mappings/ioc_mapping.json
> +          "type": "text",
why cant name be keyword like id?

2024-06-05 19:38 UTC, eirsep commented on src/main/resources/mappings/ioc_mapping.json
> +          "format": "strict_date_optional_time||epoch_millis"
do we need this restriction?

2024-06-05 19:38 UTC, eirsep commented on src/main/resources/mappings/ioc_mapping.json
> +          "format": "strict_date_optional_time||epoch_millis"
do we need this restriction?

2024-06-05 19:38 UTC, eirsep requested changes
can you check some minor comments?

2024-06-06 01:20 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/action/FetchIocsActionResponse.java
> +        iocs.forEach( ioc -> this.iocs.add(new IocDto(ioc)));
Should this be done in transport/service class?

2024-06-07 21:23 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/FetchIocsActionResponse.java
> +        iocs.forEach( ioc -> this.iocs.add(new IocDto(ioc)));
@jowg-amazon It can be. The `FetchIocsActionResponse` object is just a placeholder I've been using to test the changes. We can refactor and remove it before launch.

2024-06-07 21:30 UTC, AWSHurneyt commented on src/main/resources/mappings/ioc_mapping.json
> +          "type": "text",
Revised to keyword type.

2024-06-07 21:35 UTC, AWSHurneyt commented on src/main/resources/mappings/ioc_mapping.json
> +          "format": "strict_date_optional_time||epoch_millis"
We use similar format for the mappings of some other plugin assets (e.g., [detectors](https://github.com/opensearch-project/security-analytics/blob/main/src/main/resources/mappings/detectors.json#L70)). Did you have another format in mind?

For now, I've revised this to `strict_date_time||epoch_millis`. My thoughts are that the create date should be required whereas the modified date could be null if the entry hasn't been updated.

2024-06-07 21:35 UTC, AWSHurneyt commented on src/main/resources/mappings/ioc_mapping.json
> +          "format": "strict_date_optional_time||epoch_millis"
We use similar format for the mappings of some other plugin assets (e.g., [detectors](https://github.com/opensearch-project/security-analytics/blob/main/src/main/resources/mappings/detectors.json#L70)). Did you have another format in mind?

2024-06-07 21:48 UTC, AWSHurneyt commented
> can you check some minor comments?

@eirsep Responded.

2024-06-13 00:12 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/FetchIocsActionResponse.java
> +public class FetchIocsActionResponse extends ActionResponse implements ToXContentObject {
NIT: let's keep consistent naming: ListIocsResponse?

2024-06-13 00:13 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/IOC.java
> +public class IOC implements Writeable, ToXContentObject {
how come Ioc is a concrete class and also STIX2Ioc?

2024-06-13 00:14 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/IocDto.java
>      public static IocDto parse(XContentParser xcp, String id) throws IOException {
this defeats the purpose of having separate classes for DTO and the model.. if there is ever a divergence we would end up having to re-write this method

2024-06-13 00:29 UTC, eirsep reviewed
Plz invoke IocService from TIFConfigService

2024-06-13 00:31 UTC, merged