job scheduler
opensearch-project/security-analytics pull request #1054
Opened 2024-06-04 17:04 UTC by jowg-amazon

### Description
This PR adds the skeleton for the job scheduler as well as some outline for integrating with IOC creation. It also adds in the delete and update functions that will be used for the APIs.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-07 01:44 UTC, eirsep requested changes

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +        return TIFSourceConfigRunner.getJobRunnerInstance();
if there is only one job runner why are we restricting it to threat intel stuff ?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +public class TIFSourceConfigRunner implements ScheduledJobRunner {
shoudlnt runner be generic and accept tifsourceconfig updation as one of possibly multiple jobs

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +public class TIFSourceConfigRunner implements ScheduledJobRunner {
rename to SAPJobRunner?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected Runnable updateJobRunner(final SATIFSourceConfig SaTifSourceConfig) {
NIT: why is this called "updateJobRunner" .. sounds like we are updating the jobrunner itself?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected Runnable updateJobRunner(final SATIFSourceConfig SaTifSourceConfig) {
SaTifSourceConfig - lower case variable name

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected void updateJobParameter(final SATIFSourceConfig SaTifSourceConfig, final Runnable renewLock, ActionListener<AcknowledgedResponse> listener) {
lower case variable name

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +        SaTifSourceConfigService.getTIFSourceConfig(SaTifSourceConfig.getId(), ActionListener.wrap(
why are we fetching job .. we seem to already have pojo avaialble?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                                        }, listener::onFailure
log error dont use lambda

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                listener::onFailure
log error dont use lambda

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                                        }, listener::onFailure
log job id

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                listener::onFailure
log job id

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                    }, listener::onFailure
log errors . never use lambda

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +            listener.onFailure(e);
error log?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                        throw new ResourceNotFoundException("No source config exist");
log id?

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                            }, e -> {
error logs

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                                            }, listener::onFailure
eror logs

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                                            }, listener::onFailure
plz check and add everywhere

2024-06-07 01:44 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +    private void markSourceConfigAsActionFailed(final SATIFSourceConfig SaTifSourceConfig, TIFJobState state, ActionListener<IndexResponse> actionListener) {
why is state a method param? shouldnt it be failed??

2024-06-07 18:00 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +    private void markSourceConfigAsActionFailed(final SATIFSourceConfig SaTifSourceConfig, TIFJobState state, ActionListener<IndexResponse> actionListener) {
Was thinking that this method can also be reused to set the state to `REFRESH_FAILED` in the future.

2024-06-07 18:05 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected Runnable updateJobRunner(final SATIFSourceConfig SaTifSourceConfig) {
Will rename all variable names in follow up PR so that it doesn't add merge conflicts

2024-06-07 18:05 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected void updateJobParameter(final SATIFSourceConfig SaTifSourceConfig, final Runnable renewLock, ActionListener<AcknowledgedResponse> listener) {
see above

2024-06-07 18:05 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +        SaTifSourceConfigService.getTIFSourceConfig(SaTifSourceConfig.getId(), ActionListener.wrap(
If a delete request comes in as this update task is waiting for other tasks to complete, the source config may have been deleted so we do this check to make sure that the config still exists. Will also revisit this when I figure out the locking.

2024-06-07 18:45 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String JOB_TYPE = "opensearch_sap_job";
This is the name that gets registered with the job scheduler from security analytics

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +    protected Runnable updateJobRunner(final SATIFSourceConfig SaTifSourceConfig) {
renamed to `retrieveLockAndUpdateConfig` for more clarity

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                                        }, listener::onFailure
changed

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                listener::onFailure
changed

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                    }, listener::onFailure
changed

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +            listener.onFailure(e);
added

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                        throw new ResourceNotFoundException("No source config exist");
added

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                            }, e -> {
added

2024-06-07 18:46 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                                            }, listener::onFailure
added

2024-06-07 20:40 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +        return TIFSourceConfigRunner.getJobRunnerInstance();
Added a generic security analytics job runner so that we can register different types of jobs.

2024-06-07 20:40 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +public class TIFSourceConfigRunner implements ScheduledJobRunner {
see above

2024-06-10 21:02 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +        SaTifSourceConfigService.getTIFSourceConfig(SaTifSourceConfig.getId(), ActionListener.wrap(
why not just catch a resource not found exception while updating and handle that

2024-06-10 21:31 UTC, eirsep approved these changes

2024-06-11 19:09 UTC, AWSHurneyt approved these changes
@jowg-amazon Overall LGTM. Left some non-blocking comments.

2024-06-11 19:09 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
> +            lockService.acquireLock(request.getTIFConfigDto().getName(), LOCK_DURATION_IN_SECONDS, ActionListener.wrap(lock -> {
Clarification question:
Why refactor to `getName` here? Does the create flow have checks in place to ensure names are unique?

2024-06-11 19:09 UTC, AWSHurneyt commented on src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
> +        Thread.sleep(80000);
Not blocking, but would using `waitUntil` be preferred over `sleep`? E.g., https://github.com/opensearch-project/alerting/pull/1242/files#diff-e18e70d5376f5f0d2c4672fb52529f02b1b0d99a5ee6a426003b8d86647b0ca6R75

2024-06-11 19:44 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/transport/TransportIndexTIFSourceConfigAction.java
> +            lockService.acquireLock(request.getTIFConfigDto().getName(), LOCK_DURATION_IN_SECONDS, ActionListener.wrap(lock -> {
Changing back to `getId`, had changed it to getName when testing

2024-06-11 20:02 UTC, jowg-amazon commented on src/test/java/org/opensearch/securityanalytics/resthandler/SATIFSourceConfigRestApiIT.java
> +        Thread.sleep(80000);
changed to waitUntil instead of sleep

2024-06-11 20:09 UTC, merged