Implemented ListIOCs API.
opensearch-project/security-analytics pull request #1064
Opened 2024-06-11 05:24 UTC by AWSHurneyt

### Description
Implemented ListIOCs API.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-11 19:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionResponse.java
> +    private List<STIX2IOCDto> hits;
iocs?

2024-06-11 19:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionResponse.java
> +    public static String TOTAL_HITS_FIELD = "total_hits";
total

2024-06-12 23:15 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionResponse.java
> +    public static String TOTAL_HITS_FIELD = "total_hits";
Revised.

2024-06-12 23:15 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionResponse.java
> +    private List<STIX2IOCDto> hits;
Revised.

2024-06-17 19:17 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsAction.java
> +    public static final String NAME = "cluster:admin/opensearch/securityanalytics/iocs/list";
Including https://github.com/opensearch-project/security-analytics/pull/1077#discussion_r1640330582
> should we call this `ioc/_search` or just `cluster:admin/opensearch/securityanalytics/iocs` is also good enough i guess
> 
> let's standardize all list apis...

@eirsep I believe we plan to have a separate SearchIOCs API which will support receiving a query in the request body (similar to the SearchMonitor API), so I was reserving the `_search` route for that. `iocs/list` follows the pattern used by the ListCorrelations API, but we can change this if needed.
https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/main/java/org/opensearch/securityanalytics/action/ListCorrelationsAction.java#L11

2024-06-17 19:22 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
> +    private String sortString;
Including https://github.com/opensearch-project/security-analytics/pull/1077#discussion_r1640334004
> we need feedId as a parameter
> check with @amsiglan if UX would be better suited to work with a search request rather than params?

@eirsep Added `feedId` to the request object. I believe @amsiglan mentioned that a list API would be more useful for the UI table, but I'll sync with him to confirm.

2024-06-17 23:35 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsAction.java
> +    public static final String NAME = "cluster:admin/opensearch/securityanalytics/iocs/list";
we need the search Ioc’s api.. that’s more flexible and if we are starting out with only one of these it should be the search API

2024-06-17 23:37 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String LIST_IOCS_URI = PLUGINS_BASE_URI + "/iocs/list";
list api should just `PLUGINS_BASE_URI + "/iocs"`

2024-06-17 23:38 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                        listener.onFailure(SecurityAnalyticsException.wrap(e));
log error

2024-06-17 23:42 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java
> +        String search = request.param(ListIOCsActionRequest.SEARCH_FIELD, "");
what is search field?

2024-06-17 23:46 UTC, eirsep requested changes

2024-06-17 23:46 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                                .field(STIX2_IOC_NESTED_PATH + STIX2IOC.NAME_FIELD)
can we remove nesting?

2024-06-18 00:03 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String LIST_IOCS_URI = PLUGINS_BASE_URI + "/iocs/list";
Revised.

2024-06-18 00:03 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                        listener.onFailure(SecurityAnalyticsException.wrap(e));
Revised.

2024-06-18 21:35 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                                .field(STIX2_IOC_NESTED_PATH + STIX2IOC.NAME_FIELD)
I think we still need to include it.

Elsewhere in the code, it looks like we need to provide the nested path; even when using `QueryBuilders.nestedQuery()`.
https://github.com/opensearch-project/security-analytics/blob/feature/threat_intel/src/main/java/org/opensearch/securityanalytics/transport/TransportIndexCustomLogTypeAction.java#L449

The GetAlerts API doesn't need to provide a nested path
https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/transport/TransportGetAlertsAction.kt#L138

However, the alerts values aren't nested in an alert object in the mappings for that system index.
https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/resources/org/opensearch/alerting/alerts/alert_mapping.json#L28

2024-06-18 23:39 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsAction.java
> +    public static final String NAME = "cluster:admin/opensearch/securityanalytics/iocs/list";
Will implement a search IOC API separately.

2024-06-18 23:41 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
> +    private String feedId;
Per offline discussion, refactor this to a list of feedIds.

2024-06-18 23:52 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestListIOCsAction.java
> +        String search = request.param(ListIOCsActionRequest.SEARCH_FIELD, "");
The search field is used to support the search bar (see screenshot). Currently, it'll search the name, value, severity, create time, and modified time fields of the docs.
<img width="1266" alt="Screenshot 2024-06-18 at 4 50 42 PM" src="https://github.com/opensearch-project/security-analytics/assets/79280347/b4017c94-7689-4a65-9d36-9b2f8cc39290">

2024-06-19 07:41 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +        private final AtomicReference<Object> response;
what is this for?

2024-06-19 07:43 UTC, eirsep approved these changes

2024-06-19 07:44 UTC, merged

2024-06-19 17:23 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                                                    "Failed to parse IOC doc from hit {}", hit),
hit itself would be a byte ref or a hashcode possibly
change logged variable to hit.getId()

2024-06-19 19:38 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                                                    "Failed to parse IOC doc from hit {}", hit),
Revised in PR https://github.com/opensearch-project/security-analytics/pull/1085

2024-06-19 19:47 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
> +    private String feedId;
Addressed in PR https://github.com/opensearch-project/security-analytics/pull/1085