Delete threat intel source config API
opensearch-project/security-analytics pull request #1066
Opened 2024-06-11 21:20 UTC by jowg-amazon

### Description
Architecture for delete threat intel source config API
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-11 21:34 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SADeleteTIFSourceConfigRequest.java
> +        return null;
Should there be a check here to assert that the `id` is not null or empty?

2024-06-11 21:34 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigManagementService.java
> +                                log.debug("Successfully deleted threat intel source config [{}]", SaTifSourceConfig.getId());
Not blocking, but should we consider making this an info-level log?

2024-06-11 21:34 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/service/SATIFSourceConfigService.java
> +                        log.debug("Deleted threat intel source config [{}] successfully", SaTifSourceConfig.getId());
Same question as above.

2024-06-11 21:43 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SADeleteTIFSourceConfigRequest.java
> +        return null;
Added a check to ensure id exists

2024-06-11 23:08 UTC, AWSHurneyt approved these changes

2024-06-12 19:06 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SADeleteTIFSourceConfigResponse.java
> +    private final RestStatus status;
what status implies deleted?

2024-06-12 19:06 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/Constants.java
> +    public static final String SOURCE_CONFIG_ID = "source_config_id";
MEGA-NIT: threat_intel_source_config_id?

2024-06-12 19:07 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestDeleteTIFSourceConfigAction.java
> +        String SaTifSourceConfigId = request.param(SOURCE_CONFIG_ID, SATIFSourceConfigDto.NO_ID);
lower case letter to begin variable name

2024-06-12 19:08 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestDeleteTIFSourceConfigAction.java
> +        if (SaTifSourceConfigId == null || SaTifSourceConfigId.isEmpty()) {
nit: Stringutils.isBlank() instead

2024-06-12 19:10 UTC, eirsep requested changes
if there is only one config and it it's being deleted we need to ensure there are no jobs
Fail the delete request of the config saying plz delete all threat intel monitors before deleting the last config

2024-06-13 17:29 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SADeleteTIFSourceConfigResponse.java
> +    private final RestStatus status;
if the delete response is `OK` then the document is deleted successfully.

2024-06-13 18:57 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/Constants.java
> +    public static final String SOURCE_CONFIG_ID = "source_config_id";
changed to `threat_intel_source_config_id`

2024-06-13 18:57 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestDeleteTIFSourceConfigAction.java
> +        if (SaTifSourceConfigId == null || SaTifSourceConfigId.isEmpty()) {
changed

2024-06-13 18:57 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestDeleteTIFSourceConfigAction.java
> +        String SaTifSourceConfigId = request.param(SOURCE_CONFIG_ID, SATIFSourceConfigDto.NO_ID);
fixed

2024-06-13 20:44 UTC, jowg-amazon commented
> if there is only one config and it it's being deleted we need to ensure there are no jobs Fail the delete request of the config saying plz delete all threat intel monitors before deleting the last config

Added a method `checkAndEnsureThreatIntelMonitorsDeleted` that checks if the source config to be deleted is the last one and if so, makes sure that all threat intel monitors have been deleted. Otherwise it throws an exception.

2024-06-13 23:31 UTC, eirsep approved these changes

2024-06-13 23:33 UTC, merged