Refresh API and adds Update TIF Source Config logic
opensearch-project/security-analytics pull request #1078
Opened 2024-06-14 23:09 UTC by jowg-amazon

### Description
This PR adds the refresh API and refactors some logic from the source config runner to the service class. It also adds logic to update the source config.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-17 07:07 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +public class SARefreshTIFSourceConfigAction extends ActionType<AcknowledgedResponse> {
just `RefreshTIFSourceConfigAction` ?

2024-06-17 07:08 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +import org.opensearch.action.support.master.AcknowledgedResponse;
plz use  org.opensearch.extensions.AcknowledgedResponse

2024-06-17 07:52 UTC, eirsep requested changes

2024-06-17 07:52 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +        SaTifSourceConfigManagementService.refreshTIFSourceConfig(SaTifSourceConfig.getId(), ActionListener.wrap(
why did we remove the existing update code and call refresh in `updateSourceConfigAndIOCs`?

2024-06-17 07:52 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestRefreshTIFSourceConfigAction.java
> +        return List.of(new Route(RestRequest.Method.POST, String.format(Locale.getDefault(), "%s/refresh/{%s}", SecurityAnalyticsPlugin.THREAT_INTEL_SOURCE_URI, THREAT_INTEL_SOURCE_CONFIG_ID)));
should be `"%s/%s/refresh"`

and why is there a surrounding curly braces on the 2nd %s placeholder??

2024-06-17 17:31 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestRefreshTIFSourceConfigAction.java
> +        return List.of(new Route(RestRequest.Method.POST, String.format(Locale.getDefault(), "%s/refresh/{%s}", SecurityAnalyticsPlugin.THREAT_INTEL_SOURCE_URI, THREAT_INTEL_SOURCE_CONFIG_ID)));
Should the route include `_` (e.g., `%s/{%s}/_refresh`), similar to the execute monitor API?
https://opensearch.org/docs/latest/observing-your-data/alerting/api/#run-monitor

2024-06-17 17:40 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +public class SARefreshTIFSourceConfigAction extends ActionType<AcknowledgedResponse> {
There should be an implementation of this in sa commons that `SARefreshTIFSourceConfigAction` will extend from but will write all the interfaces at once in a separate PR

2024-06-17 17:41 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +import org.opensearch.action.support.master.AcknowledgedResponse;
`org.opensearch.extensions.AcknowledgedResponse` is not allowed as the abstract class type, we currently use `org.opensearch.action.support.master.AcknowledgedResponse` everywhere in the repo when returning just the actionResponse https://github.com/opensearch-project/security-analytics/blob/362f0d6c1283756ae21ff9858bcf88daf938d67e/src/main/java/org/opensearch/securityanalytics/action/DeleteCorrelationRuleAction.java#L12
I can add a response class that returns different information (like config id etc...) if `org.opensearch.extensions.AcknowledgedResponse` shouldn't be used

2024-06-17 17:54 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/resthandler/RestRefreshTIFSourceConfigAction.java
> +        return List.of(new Route(RestRequest.Method.POST, String.format(Locale.getDefault(), "%s/refresh/{%s}", SecurityAnalyticsPlugin.THREAT_INTEL_SOURCE_URI, THREAT_INTEL_SOURCE_CONFIG_ID)));
We seem to add the curly braces around any ID field throughout the repo so did it for consistency. Will change the ordering so that it's `%s/{%s}/_refresh`

2024-06-17 17:55 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +        SaTifSourceConfigManagementService.refreshTIFSourceConfig(SaTifSourceConfig.getId(), ActionListener.wrap(
Originally refactored this becaues the logic for the refresh api and the job scheduler were the same but if we're adding a background job to delete unused indices realizing the logic might be slightly different now. Changing it back to existing code but may refactor again later to see what logic can be reused

2024-06-17 23:55 UTC, eirsep requested changes
For Create tif source config API:
we need to 
1. create tif source config and index it with state as CREATING
2. invoke ioc download.
3. update as AVAILABLE if download succeeds. else delete feed from index and return ERROR.

2024-06-17 23:57 UTC, AWSHurneyt commented
> For Create tif source config API: we need to
> 
> 1. create tif source config and index it with state as CREATING
> 2. invoke ioc download.
> 3. update as AVAILABLE if download succeeds. else delete feed from index and return ERROR.

This is in reference to https://github.com/opensearch-project/security-analytics/pull/1077/files#diff-e2af2dcb9a2eff5b384869ea9c85d1649dd3b63ad03ebe2963c1f304dec40402R114

2024-06-18 08:22 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                        log.error("Invalid TIF job state. Expecting {} but received {}", TIFJobState.AVAILABLE, saTifSourceConfigResponse.getState());
what if state is not "AVAILABLE>

2024-06-18 17:54 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigRequest.java
> +    private final Long version;
taking version out for now as it's not being used in the refresh flow

2024-06-18 17:57 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/jobscheduler/TIFSourceConfigRunner.java
> +                        log.error("Invalid TIF job state. Expecting {} but received {}", TIFJobState.AVAILABLE, saTifSourceConfigResponse.getState());
If state isn't available, then it could mean that it's either currently refreshing, deleting, retrying (state will be added in later PR), or that something has failed (create_failed, refresh_failed). In these scenarios we just want to skip the current run of the job scheduler

2024-06-18 17:58 UTC, jowg-amazon commented
@eirsep Updated the logic when creating the source config so that we index the CREATING state first before downloading and saving the IOCS, added a TODO to delete ioc indices if failed

2024-06-18 20:07 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +import org.opensearch.action.support.master.AcknowledgedResponse;
nvm lets go with this

2024-06-18 20:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/threatIntel/action/SARefreshTIFSourceConfigAction.java
> +public class SARefreshTIFSourceConfigAction extends ActionType<AcknowledgedResponse> {
actions won't have implementations.
just derive action names from sa commons

2024-06-19 21:05 UTC, AWSHurneyt approved these changes

2024-06-19 21:05 UTC, merged