ListIOCs API support lists of feedIds, and types.
opensearch-project/security-analytics pull request #1085
Opened 2024-06-19 19:37 UTC by AWSHurneyt

### Description
Made feedId, and type params of ListIOCsActionRequest support lists of strings.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-19 19:49 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    private Long numIocMatches;
let's call it findings

2024-06-19 19:50 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    public static String NUM_IOC_MATCHES_FIELD = "num_ioc_matches";
num_findings

2024-06-19 19:50 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +        if (numIocMatches != null) builder.field(NUM_IOC_MATCHES_FIELD, numIocMatches);
nit: this is fully correct but we can just add `.field(NUM_IOC_MATCHES_FIELD, numIocMatches)` even if it's null right?

2024-06-19 19:51 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String IOCS_URI = PLUGINS_BASE_URI + "/iocs";
nit: variable name should still be LIST_IOCS 
api for list and get dont usually have list and get in the api endpoint based on rest api naming

2024-06-19 19:55 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
> +        this.types = types.stream().map(t -> t.toLowerCase(Locale.ROOT)).collect(Collectors.toList());
null check missing

2024-06-19 19:55 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +            if (request.getTypes().stream().noneMatch(type -> ListIOCsActionRequest.ALL_TYPES_FILTER.equalsIgnoreCase(type))) {
null check missing

2024-06-19 19:56 UTC, eirsep requested changes
minor comments

2024-06-19 20:20 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    private Long numIocMatches;
Will rename to `numFindings` based on suggestion here https://github.com/opensearch-project/security-analytics/pull/1085#discussion_r1646637412

2024-06-19 20:22 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +        if (numIocMatches != null) builder.field(NUM_IOC_MATCHES_FIELD, numIocMatches);
We could, but the JSON payload would contain `"num_ioc_matches": null` as opposed to excluding that field. The Number of findings might not be necessary to provide for all uses of the DTO, so I thought it would make sense to exclude the field to avoid confusion when looking at the JSON.

I don't mind including it though.

2024-06-19 20:23 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/ListIOCsActionRequest.java
> +        this.types = types.stream().map(t -> t.toLowerCase(Locale.ROOT)).collect(Collectors.toList());
Good catch, will add.

2024-06-19 20:50 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    public static String NUM_IOC_MATCHES_FIELD = "num_ioc_matches";
Revised.

2024-06-19 20:55 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +            if (request.getTypes().stream().noneMatch(type -> ListIOCsActionRequest.ALL_TYPES_FILTER.equalsIgnoreCase(type))) {
Good catch. Revised.

2024-06-19 21:00 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +        if (numIocMatches != null) builder.field(NUM_IOC_MATCHES_FIELD, numIocMatches);
good point.. can this default to 0?
also i thought this was num_ioc_matches_in_last_24h

2024-06-19 21:02 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +        if (numIocMatches != null) builder.field(NUM_IOC_MATCHES_FIELD, numIocMatches);
Hmm would a default value of 0 be misleading in cases where the DTO is being used outside of the ListIOCs API?

2024-06-19 21:05 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    public static String NUM_FINDINGS_FIELD = "num_findings";
```
DetailedIocDto {
     STIXDTO
     numIocMAtches
     <some other stat1>
     <some other stat2>
     .....
}
```

Can we use this instead

2024-06-19 21:06 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    public static String NUM_FINDINGS_FIELD = "num_findings";
instead of modifying the transfer object of ioc itself
gives more flexibility to use DTO elsewhere without worrying about stats being out of context as mentioned by @AWSHurneyt

2024-06-19 21:25 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +    public static String NUM_FINDINGS_FIELD = "num_findings";
Implemented.

2024-06-19 21:25 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +        if (numIocMatches != null) builder.field(NUM_IOC_MATCHES_FIELD, numIocMatches);
See conversation below https://github.com/opensearch-project/security-analytics/pull/1085#discussion_r1646688097

2024-06-19 21:28 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDto.java
> +public class DetailedSTIX2IOCDto extends STIX2IOCDto implements Writeable, ToXContentObject {
no need to `extends STIX2IOCDto`

2024-06-19 21:35 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/DetailedSTIX2IOCDto.java
> +public class DetailedSTIX2IOCDto extends STIX2IOCDto implements Writeable, ToXContentObject {
Revised.

2024-06-21 01:51 UTC, eirsep approved these changes

2024-06-21 18:59 UTC, eirsep approved these changes

2024-06-21 22:03 UTC, merged