Implemented API to test s3 connection.
opensearch-project/security-analytics pull request #1091
Opened 2024-06-21 01:17 UTC by AWSHurneyt

### Description
Implemented API to test s3 connection.

This PR is dependent on PR https://github.com/opensearch-project/security-analytics-commons/pull/11
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-21 01:57 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TEST_CONNECTION_BASE_URI = PLUGINS_BASE_URI + "/test_connection";
ideally api should be `/_plugins/_sap/connections/test/s3`

2024-06-21 01:59 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/TestS3ConnectionRequest.java
> +public class TestS3ConnectionRequest extends ActionRequest implements ToXContentObject {
why si this object not like ?
```
class TestS3ConnectionRequest
     S3Config s3config
}
```

plz reuse whatever is present in the threat intel source config

2024-06-21 02:39 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportTestS3ConnectionAction.java
> +        super(TestS3ConnectionAction.NAME, transportService, actionFilters, TestS3ConnectionRequest::new);
we need S3Exception.awsErrorDetails() also?

2024-06-21 02:39 UTC, eirsep commented on src/main/plugin-metadata/plugin-security.policy
> +    permission java.io.FilePermission "${user.home}${/}.aws${/}*", "read";
are these still needed?

2024-06-21 02:39 UTC, eirsep requested changes
some comments

2024-06-21 21:45 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TEST_CONNECTION_BASE_URI = PLUGINS_BASE_URI + "/test_connection";
Revised.

2024-06-21 21:45 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportTestS3ConnectionAction.java
> +        super(TestS3ConnectionAction.NAME, transportService, actionFilters, TestS3ConnectionRequest::new);
Could you clarify what you mean by this? I did some searching in the OpenSearch project, but didn't come across `awsErrorDetails` used in transport action constructors.

2024-06-21 22:18 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/action/TestS3ConnectionRequest.java
> +public class TestS3ConnectionRequest extends ActionRequest implements ToXContentObject {
Revised.

2024-06-22 00:51 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportTestS3ConnectionAction.java
> +        super(TestS3ConnectionAction.NAME, transportService, actionFilters, TestS3ConnectionRequest::new);
Clarified offline that we should try to use the `awsErrorDetails` to provide the error message in the `doExecute` function responses.

Revising accordingly.

2024-06-22 01:35 UTC, AWSHurneyt commented on src/main/plugin-metadata/plugin-security.policy
> +    permission java.io.FilePermission "${user.home}${/}.aws${/}*", "read";
My local testing suggests we only need to add the `permission java.io.FilePermission "${user.home}${/}.aws${/}*", "read";` permission. I've removed the others.

2024-06-24 17:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TEST_CONNECTION_BASE_URI = PLUGINS_BASE_URI + "/test_connection";
apologies.. /_plugins/_sap/connections/s3/test

2024-06-24 18:18 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String TEST_CONNECTION_BASE_URI = PLUGINS_BASE_URI + "/test_connection";
Revised.

2024-06-24 18:18 UTC, eirsep approved these changes

2024-06-24 18:26 UTC, jowg-amazon approved these changes

2024-06-24 18:36 UTC, merged