Logic to delete old iocs
opensearch-project/security-analytics pull request #1094
Opened 2024-06-22 01:24 UTC by jowg-amazon

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-22 08:13 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_history_retention_period",
plugins.security_analytics.ioc.history_retention_period

2024-06-22 08:13 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +    public static final Setting<Integer> MAX_IOC_INDICES_PER_ALIAS = Setting.intSetting(
**`plugins.security_analytics.ioc.`** should be prefix

2024-06-22 08:14 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            new TimeValue(30, TimeUnit.DAYS),
set a min value of 1 day

2024-06-24 17:49 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            new TimeValue(30, TimeUnit.DAYS),
done

2024-06-24 17:49 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +    public static final Setting<Integer> MAX_IOC_INDICES_PER_ALIAS = Setting.intSetting(
changed to `ioc_indices_per_alias`

2024-06-24 17:49 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_history_retention_period",
fixed

2024-06-24 23:52 UTC, eirsep requested changes

2024-06-24 23:52 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_indices_per_alias",
`plugins.security_analytics.ioc.`

2024-06-24 23:52 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_indices_per_alias",
max_indices*

2024-06-25 20:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFeedStore.java
> +    public static final String IOC_HISTORY_WRITE_INDEX_ALIAS = IOC_INDEX_NAME_TEMPLATE + "-write";
removed history

2024-06-25 20:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_indices_per_alias",
fixed

2024-06-25 20:22 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.ioc_indices_per_alias",
fixed to `plugins.security_analytics.ioc.max_indices_per_alias`

2024-06-25 20:58 UTC, eirsep approved these changes

2024-06-25 21:04 UTC, AWSHurneyt approved these changes

2024-06-25 21:09 UTC, merged