ListIOCs API to return number of findings per IOC.
opensearch-project/security-analytics pull request #1163
Opened 2024-07-15 23:09 UTC by AWSHurneyt

### Description
Refactored ListIOCs API to return the correct number of findings for each IOC.

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-16 00:25 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +            if (request.getTable().getSearchString() != null && !request.getTable().getSearchString().isEmpty()) {
nit: `StringUtils.isBlank(<str>)`

2024-07-16 00:27 UTC, eirsep requested changes

2024-07-16 00:27 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                    GetIocFindingsRequest getFindingsRequest = new GetIocFindingsRequest(
nit: can we instead do an aggregation query where we get the map of ioc Id to num findings? prolly a bucket agg query. that way we are not limited by 10000 results problem

2024-07-16 23:36 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +                    GetIocFindingsRequest getFindingsRequest = new GetIocFindingsRequest(
As discussed offline, I'll address this in a separate PR.

2024-07-16 23:36 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/transport/TransportListIOCsAction.java
> +            if (request.getTable().getSearchString() != null && !request.getTable().getSearchString().isEmpty()) {
As discussed offline, I'll address this in a separate PR.

2024-07-16 23:37 UTC, jowg-amazon approved these changes

2024-07-17 00:36 UTC, eirsep approved these changes

2024-07-17 00:36 UTC, merged