Catch and wrap exceptions.
opensearch-project/security-analytics pull request #1198
Opened 2024-07-24 00:11 UTC by AWSHurneyt

### Description
1. Added logic to catch more exceptions, and wrap more exceptions.
2. Updated jar to reflect changes in PR https://github.com/opensearch-project/security-analytics-commons/pull/19

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-24 06:11 UTC, AWSHurneyt commented
The failing tests are in the `MapperRestApiIT` class, which shouldn't be affected by the changes in this PR. In addition, `./gradlew :integTest` succeeds locally. Will investigate the test failures.

2024-07-24 21:14 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                    try {;
nit: plz remove the semicolon

2024-07-24 21:15 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                        throw SecurityAnalyticsException.wrap(e);
plz construct exception message to say `Couldn't parse Ioc type <typestring> while deserializing Stix2Ioc <id>",

2024-07-24 21:16 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +                        throw SecurityAnalyticsException.wrap(e);
https://github.com/opensearch-project/security-analytics/pull/1198/files#r1690450982

2024-07-24 21:17 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            listener.onFailure(SecurityAnalyticsException.wrap(e));
can we construct exception with above message as `Failed to index IOCs from source config` and cause fo exception as e

2024-07-24 21:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +        } catch (IllegalArgumentException | ConnectorParsingException | RuntimeJsonMappingException e) {
thanks for adding these!

2024-07-24 21:18 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            listener.onFailure(SecurityAnalyticsException.wrap(e));
can we add above message to exception message and add `e` as cause

2024-07-24 21:21 UTC, eirsep requested changes
can we add tests?

2024-07-24 21:34 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                    try {;
Good catch. Removed.

2024-07-24 21:37 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                        throw SecurityAnalyticsException.wrap(e);
Revised.

2024-07-24 21:38 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
> +                        throw SecurityAnalyticsException.wrap(e);
Revised.

2024-07-24 22:15 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            listener.onFailure(SecurityAnalyticsException.wrap(e));
Revised.

2024-07-24 22:15 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            listener.onFailure(SecurityAnalyticsException.wrap(e));
Revised.

2024-07-24 22:24 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                        logger.error("Couldn't parse IOC type while deserializing STIX2IOC: '{}'.", typeString, e);
"Couldn't parse IOC type {} while deserializing STIX2IOC: {}",  typeString, id

I meant using this constructor for line 214 
` public SecurityAnalyticsException(String message, RestStatus status, Exception ex)`

2024-07-24 22:25 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +                    "Failed to index IOCs from source config after %s milliseconds with %s: ",
source config name needs to be loggesd.

2024-07-24 22:26 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +                    "Failed to index IOCs from source config after %s milliseconds with %s: ",
3 usages of same string. plz re-use a constant string variable

2024-07-24 22:27 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            String error = String.format("Failed to index IOCs from source config with %s: ", e.getClass().getName());
plz resuse string variable for error message

plz dont print class name just passing the error message is good enough

2024-07-24 22:27 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            String error = String.format("Failed to index IOCs from source config with %s: ", e.getClass().getName());
plz remove `e.getClass().getName())` everywhere

2024-07-24 22:27 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
>                          throw SecurityAnalyticsException.wrap(e);
plz pass message to SecurityAnalyticsException

2024-07-24 22:33 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                        logger.error("Couldn't parse IOC type while deserializing STIX2IOC: '{}'.", typeString, e);
Oh, sorry for the confusion. Revised.

2024-07-24 22:41 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +                    "Failed to index IOCs from source config after %s milliseconds with %s: ",
Revised.

2024-07-24 23:29 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +                    "Failed to index IOCs from source config after %s milliseconds with %s: ",
Revised.

2024-07-24 23:29 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/services/STIX2IOCFetchService.java
> +            String error = String.format("Failed to index IOCs from source config with %s: ", e.getClass().getName());
Revised.

2024-07-24 23:33 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOCDto.java
>                          throw SecurityAnalyticsException.wrap(e);
Revised.

2024-07-25 01:26 UTC, AWSHurneyt commented
> can we add tests?

Added a few unit tests, and an integ test. Many of the exceptions get caught following communication with S3, which we don't support automated tests for at the moment. I'll add additional tests in a separate PR.

2024-07-25 18:19 UTC, AWSHurneyt commented
I was able to reproduce the failing tests locally after adding `--refresh-dependencies` to the run command.
```
./gradlew clean && ./gradlew ':integTest' --tests "org.opensearch.securityanalytics.mapper.MapperRestApiIT --refresh-dependencies
```
These tests are currently failing on the `main` branch even without the changes in this PR; suggesting this is a pre-existing issue.

2024-07-25 20:49 UTC, eirsep approved these changes

2024-07-29 21:41 UTC, engechas commented on security-analytics-commons-1.0.0.jar
Including JARs directly is generally a bad practice as there's no easy way to tell what's in this code and how it has changed/evolved from the current source of security-analytics-commons. I'm guessing this is just a temporary bridge solution for now. I am OK with it if that's the case. Would be good to know what the plan going forward is though.

2024-07-29 21:43 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                    } catch (Exception e) {
Really minor - could create a helper method to perform this logic since it is repeated in 2 spots

2024-07-29 23:05 UTC, AWSHurneyt commented on security-analytics-commons-1.0.0.jar
Yeah this is a follow-up item I have. We **do not** want to use this jar method long-term.

2024-07-29 23:05 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/model/STIX2IOC.java
> +                    } catch (Exception e) {
I'll take this as a follow-up item, and will address it in a separate PR.

2024-07-29 23:05 UTC, merged