separate doc-level monitor query indices created by detectors
opensearch-project/security-analytics pull request #1324
Opened 2024-09-25 03:20 UTC by sbcd90

### Description
separate doc-level monitor query indices created by detectors

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [X] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [X] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security-analytics/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-25 06:46 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                new DataSources(detector.getRuleIndex() + "_chained_findings",
why do we need separate index?

2024-09-25 06:46 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +        return String.format(Locale.getDefault(), ".opensearch-sap-%s-detectors-queries-optimized-%s", logType, UUID.randomUUID());
we are moving from index patttern to index?

2024-09-25 06:48 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +            if (currentDetector.getRuleIndex().contains("optimized")) {
if name contains `optimized` shouldn't we set rule index name as `getRuleIndexOptimized` value?

is this if else condition flipped?

2024-09-25 06:49 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/DetectorThreatIntelIT.java
> -        SearchResponse response = executeSearchAndGetResponse(DetectorMonitorConfig.getRuleIndex(randomDetectorType()), request, true);
why has this been removed

2024-09-25 07:02 UTC, eirsep requested changes
what happens when someone updates a detector that doesnt have exclusive query index?

2024-09-25 07:05 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
> -        String request = "{\n" +
plz revert and fix test as necessary

2024-09-25 07:05 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -        String request = "{\n" +
plz revert

2024-09-25 11:08 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                new DataSources(detector.getRuleIndex() + "_chained_findings",
each doc-level monitor has its own query index now. So the `chained findings doc-level monitor` also has its own index.

2024-09-25 11:09 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +        return String.format(Locale.getDefault(), ".opensearch-sap-%s-detectors-queries-optimized-%s", logType, UUID.randomUUID());
no. this method is utilized by few integ tests & hence the change.

2024-09-25 11:13 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +            if (currentDetector.getRuleIndex().contains("optimized")) {
the `if-else condition` checks if the detector is already using a dedicated query index, then keep on using it. else, switch from shared query index to new dedicated query index as the detector is updated.

2024-09-25 11:15 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/DetectorThreatIntelIT.java
> -        SearchResponse response = executeSearchAndGetResponse(DetectorMonitorConfig.getRuleIndex(randomDetectorType()), request, true);
query indices are created & deleted now. So, it is difficult to assert number of queries in query index now.

2024-09-25 11:18 UTC, sbcd90 commented
> what happens when someone updates a detector that doesnt have exclusive query index?

The detector is updated to use exclusive query index.

2024-09-25 11:19 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/alerts/AlertsIT.java
> -        String request = "{\n" +
query indices are created & deleted now. So, it is difficult to assert number of queries in query index now.

2024-09-25 11:19 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -        String request = "{\n" +
query indices are created & deleted now. So, it is difficult to assert number of queries in query index now.

2024-09-26 00:49 UTC, sbcd90 commented
security tests fail as docker image not updated.

2024-09-26 01:16 UTC, eirsep commented
looks like we create aliases not indices from 'queryIndex` field in monitor datasources

2024-09-26 01:24 UTC, eirsep commented
can we add tests for scenarios

setting is **off**. create detector. verify query index name. turn **on** setting. update detector, verify query index name
setting is **on**. create detector. verify query index name. turn **off** setting. update detector, verify query index name. create new detector and verify query index(should be old style since setting is off)

2024-09-26 01:40 UTC, eirsep requested changes

2024-09-26 01:40 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +        return String.format(Locale.getDefault(), ".opensearch-sap-%s-detectors-queries*", logType);
why `*` 
this is an alias

2024-09-26 01:40 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                request.getDetector().setRuleIndex(currentDetector.getRuleIndex());
plz add comment that if we turn OFF setting after turning on, updating detector will not change from optimized to normal and we need to re-create detector

2024-09-26 01:40 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                    request.getDetector().setRuleIndex(ruleTopicIndex.substring(0, ruleTopicIndex.length() - 1));
this line is very confusing

2024-09-26 01:40 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
> +        updateClusterSetting("plugins.security_analytics.enable_detectors_with_dedicated_query_indices", "true");
are there tests with setting turned off

2024-09-26 01:40 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
> -        List<SearchHit> hits = executeSearch(".opensearch-sap-azure-detectors-queries-000001", matchAllSearchBody);
can you retain this test and add a new one - basically test for both setting turned. on and turned off

2024-09-26 01:40 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
> -        String request = "{\n" +
we should not remove this code. we lose code coverage of tests. that's an anti-pattern. let's fix these tests

2024-09-26 08:57 UTC, sbcd90 commented
> can we add tests for scenarios
> 
> setting is **off**. create 2 detectors. verify query index name. turn **on** setting. update 1 detector, verify query index name. setting is **on**. create 1 detector. verify query index name. turn **off** setting. update detector, verify query index name. create new detector and verify query index(should be old style since setting is off)

added both test cases.

1st scenario: https://github.com/sbcd90/security-analytics/blob/c514a780d4b3f65ac828e3ff868c56f46f2a82b7/src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java#L1729
2nd scenario: https://github.com/sbcd90/security-analytics/blob/c514a780d4b3f65ac828e3ff868c56f46f2a82b7/src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java#L1831

2024-09-26 08:57 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorMonitorRestApiIT.java
> -        String request = "{\n" +
fixed it.

2024-09-26 08:58 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperRestApiIT.java
> -        List<SearchHit> hits = executeSearch(".opensearch-sap-azure-detectors-queries-000001", matchAllSearchBody);
added scenario for flag turned off in test cases. updated this test case to fetch queries from index pattern.

2024-09-26 09:01 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/SecurityAnalyticsRestTestCase.java
> +        updateClusterSetting("plugins.security_analytics.enable_detectors_with_dedicated_query_indices", "true");
added a test for setting turned off.

2024-09-26 09:01 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                request.getDetector().setRuleIndex(currentDetector.getRuleIndex());
added a comment. added a test too.

2024-09-26 09:02 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +        return String.format(Locale.getDefault(), ".opensearch-sap-%s-detectors-queries*", logType);
fixed it.

2024-09-26 09:03 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +                request.getDetector().setRuleIndex(ruleTopicIndex.substring(0, ruleTopicIndex.length()-1));
`ruleIndex` is changing to dedicated `ruleIndexOptimzied` now. Thats why `if-else condition`.

2024-09-26 09:06 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
> +                        .map(logType -> DetectorMonitorConfig.getRuleIndex(logType) + "*")
shouldn't this be detector specific?
why do we have this method? `getAllRuleIndices`

2024-09-26 16:19 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/util/RuleTopicIndices.java
> +                        .map(logType -> DetectorMonitorConfig.getRuleIndex(logType) + "*")
a single index template containing specific settings for sigma rule executions are applied to all rule indices.

2024-09-26 16:50 UTC, eirsep commented
CI is failing

2024-09-26 17:50 UTC, sbcd90 commented
> CI is failing

ci passed now.

2024-09-26 19:44 UTC, eirsep approved these changes

2024-09-26 19:45 UTC, eirsep commented
Security tests failed

2024-09-26 20:48 UTC, AWSHurneyt approved these changes

2024-09-26 20:49 UTC, merged

2024-11-21 18:05 UTC, sbcd90 commented
hi @ELKHostmaster , please bounce(stop and start) OpenSearch process in every data node. This would cleanup those tasks. 
Please create detectors on a `rolling index alias with write index pointing to the current index where data is ingested`(https://opensearch.org/docs/latest/im-plugin/index-alias/#index-alias-options )

2024-11-21 18:17 UTC, mimicbox commented
Hi @sbcd90 

I am having a simmilar issue to this and have been following this. I want to try your suggestion but the part I do not get it is e-

> create detectors on a rolling index alias with write index pointing to the current index where data is ingested

How do I define this during detector creation? I use the API to create detectors. Are you talking about the index pattern you define in the inputs.detector_input.indices value? I currently use an alias that points to a datastream.

Thank you for any help at all!

2024-11-21 18:24 UTC, sbcd90 commented
hi @mimicbox , if you're currently using an `index pattern` with your detector, just change it to an `index alias` instead. the term `rolling` refers to `index alias with rollovers`. 
e.g.
we have an index,

api_output-000001 -> currently points as write index for index alias api_output
now, index rolls over after sometime to ,
api_output-000002 , write index also moves if you're using an ISM policy for rollover. https://opensearch.org/docs/latest/im-plugin/ism/policies/#rollover

provide `api_output` as input to the detector. if there is no auto suggestion, manually type it into the text box.
Lastly, keep index alias name `api_output` a prefix of the index names behind it e.g `api_output-000001`, `api_output-000002`... so on, or `api_output-test-000001`, `api_output-test-000002`... so on.

2024-11-21 18:40 UTC, ELKHostmaster commented
@sbcd90   If I understand correctly, your saying point the detector to the index alias and use ISM to rollover the indices at regular intervals.

I'm already doing that. There is something related to the fan-out change introduced in 2.14 that I think has really caused the performance issues. 

Is this fixed in 2.18? Is upgrading from 2.16 a possible solution?

2024-11-21 18:56 UTC, sbcd90 commented
@ELKHostmaster , are you using Sigma Aggregation Rules?

2024-11-21 19:03 UTC, ELKHostmaster commented
@sbcd90  do you mean - using any of the aggregation functions in sigma rules (https://help.sigmacomputing.com/docs/aggregate-functions) ?

No, I dont believe so but I am scanning through them now.

2024-11-21 19:04 UTC, ELKHostmaster commented
No correlation rules either. I've stripped it down to just our sigma detections as we've been trying to get to the bottom of the issue for the last month.

2024-11-21 19:07 UTC, sbcd90 commented
hi @ELKHostmaster , please bounce(stop and start) OpenSearch process in every data node. This would cleanup those tasks.
please re-create(delete & create) the detectors. This will help cleanup old metadata.
I would suggest move to an odd release. e.g, 2.15 or 2.17 before doing these steps. They will have the latest fixes.

2024-11-21 19:15 UTC, ELKHostmaster commented
@sbcd90   thank you. yes, I have stopped/started every data node several times over the last month. its the only way to keep the cluster running at this point. I'm currently on 2.16

I thought this fix was added in 2.18. Are you saying it was backported to 2.17.1 ?  I didn't think that backports resulted in a new release package being built. So, I didn't think the fix would be included. 

Also, when you say "odd" release... is there something different about odd/even releases?

Thanks again for the responses!

2024-11-21 19:19 UTC, sbcd90 commented
hi @ELKHostmaster , i dont think data nodes need to be stopped/started frequently. i would say take a thread dump of a data node when doc-level fanout tasks are stuck. That would help root cause the issue.

yes. i think all these fixes should be in `2.18`. But to stay up-to-date with future fixes, following an odd release helps.

2024-11-22 03:14 UTC, ELKHostmaster commented
@sbcd90  Good evening. I waited until a couple data nodes got really busy and took jstack dumps for you to look at. I also included a list of tasks running on the cluster. You can see a lot of tasks are running for 8 hours now and growing since the last reboot of the nodes. I appreciate any help you can give. Thanks!
[Uploading data-13.txt…]()

2024-11-26 15:52 UTC, ELKHostmaster commented
@sbcd90  Good morning. Could I ask a favor of you? Could you take a look at the thread dumps above and see if the issue is related to the fanout change? Our cluster is unusable right now with detectors enabled/running. Circuit breaker issues, java heap exceptions, nodes dropping out, 99% cpu on data nodes, etc. This was an upgrade from 2.13 where everything was fine. The only change was upgrading to 2.16. Same detectors/rules, etc. 

Do you think the fixes to fanout in 2.18 will help us? 

Thank You in advance!