Add validation for threat intel source config
opensearch-project/security-analytics pull request #1393
Opened 2024-10-25 14:22 UTC by jowg-amazon

### Description
Add source config validation so source config cannot be created without valid `name`, `type`, `format`, `source`, and `ioc type`. Additionally allows source configs with null values to still be read and deleted.

### Related Issues
Resolves #1366

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/security-analytics/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-25 20:51 UTC, eirsep approved these changes

2024-10-25 20:51 UTC, eirsep requested changes
can we add test to verify https://github.com/opensearch-project/security-analytics/issues/1366 is solved

2024-10-29 22:51 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
>      public List<String> validateSourceConfigDto(SATIFSourceConfigDto sourceConfigDto) {
As a follow-up item, let's add validation for the refresh frequency.

2024-10-29 22:51 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
> +        if (sourceConfigDto.getName() == null || sourceConfigDto.getName().isEmpty()) {
@jowg-amazon could we add length restrictions? The frontend uses this validation for names.
https://github.com/opensearch-project/security-analytics-dashboards-plugin/blob/main/public/utils/validation.ts#L7C14-L7C33

2024-10-29 22:51 UTC, AWSHurneyt commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
> +        if (sourceConfigDto.getFormat() == null || sourceConfigDto.getFormat().isEmpty()) {
We may need to add length validation for this as well. Unless this gets validated somewhere downstream, the config could be created via backend API with something like 300k characters; which could disrupt functionality.

2024-10-29 23:23 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
> +        if (sourceConfigDto.getName() == null || sourceConfigDto.getName().isEmpty()) {
added validation for names based on how frontend currently validates the name

2024-10-29 23:23 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/threatIntel/common/SourceConfigDtoValidator.java
> +        if (sourceConfigDto.getFormat() == null || sourceConfigDto.getFormat().isEmpty()) {
Added length validation

2024-10-29 23:26 UTC, jowg-amazon commented
> can we add test to verify #1366 is solved

Added parsing tests to make sure null fields can be parsed

2024-10-30 04:13 UTC, AWSHurneyt approved these changes
Changes LGTM. Approving assuming other's comments are addressed.

2024-10-30 15:03 UTC, eirsep approved these changes

2024-10-30 15:03 UTC, merged