ISSUE-19: Updated CONTRIBUTING.md with information for MacOSX devs including the gradlex Shell Script
opensearch-project/security-analytics pull request #21
Opened 2022-07-22 18:53 UTC by okram

### Description
The following shell script is intended to make the MacOSX developer experience easier. It uses a Linux/Gradle Docker image for the build environment, thus enabling `integTest` to be run on MacOSX. The mechanics of the script as well as a pointer to the script have been provided in `CONTRIBUTING.md`.
 
### Issues Resolved
#19 Complete.
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [N/A] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-25 17:44 UTC, getsaurabh02 requested changes

2022-07-25 17:44 UTC, getsaurabh02 commented on CONTRIBUTING.md
> +The Security Analytics Plugin (SAP) depends on the [Alerting Plugin](https://opensearch.org/docs/latest/monitoring-plugins/alerting/index/) (Alerting). The relationship isn't a common software API de
Since this will not be a direct dependency, as plugin will depend on common-utils package for the desired interfaces. Also we will have multiple of these dependencies in future. So lets make it a more generic statement, such as 

```The Security Analytics Plugin (SAP) depends on other OpenSearch Plugins for the execution of transport actions (such as Alerting Plugin).```

2022-07-25 17:44 UTC, getsaurabh02 commented on CONTRIBUTING.md
> +* **NOTE**: The Linux platform requirement only applies to integration testing (`integTest`), where the test suites spawn a cluster, load the respective SAP and Alerting plugins, and then proceed exe
Should we have a top level heading to separate out developer notes for Mac Users?

2022-07-25 17:44 UTC, getsaurabh02 commented on bin/gradlex
> +# Usage: gradlex build
Should we add comment to reason out the need for ``gradlex`` being added here

2022-07-25 17:44 UTC, getsaurabh02 commented on bin/gradlex
> +DEFAULT_DOCKER_IMAGE=gradle:7.4.2-jdk11-focal
Do we need to upgrade this as well, every-time the gradle or jdk version is upgraded for the plugin?

2022-07-25 17:44 UTC, getsaurabh02 commented on bin/gradlex
> +  echo "
nit: indent

2022-07-25 17:44 UTC, getsaurabh02 commented on bin/gradlex
> +fi
nit : indentation

2022-07-27 20:31 UTC, getsaurabh02 commented
Thanks for the changes @okram. Have added few comments/suggestions to consider.

2022-08-10 06:43 UTC, okram commented on CONTRIBUTING.md
> +* **NOTE**: The Linux platform requirement only applies to integration testing (`integTest`), where the test suites spawn a cluster, load the respective SAP and Alerting plugins, and then proceed exe
First off, sorry for the delay. I never saw your comments.

While `gradlex` is cool, I don't think it should exist. Why doesn't OpenSearch release SNAPSHOT `darwin64.tar.gz`s in coordination with the Linux `arch.tar.gz` builds? If there is some fundamental reason that is insurmountable, then I think a `For Mac Users` section would be smart. 

In a world where `gradlex` is needed, note that #24 becomes ever more pressing as accessing the Docker volume for server logs is yet another step in testing complexity.

2022-08-10 06:44 UTC, okram commented on bin/gradlex
> +# Usage: gradlex build
Apologies. I don't understand what you are asking.

2022-08-10 06:47 UTC, okram commented on bin/gradlex
> +DEFAULT_DOCKER_IMAGE=gradle:7.4.2-jdk11-focal
Yes. Another reason why `gradlex` should not exist. More stuff to keep in sync :). However, now I'm wondering if there is a way for this `DEFAULT_DOCKER_IMAGE` system property to be specified by `build.gradle` via an introspection on what JVM and gradle the build file requires. ?

2023-05-18 16:57 UTC, getsaurabh02 commented
@okram Are we still working on it and would you like to contribute this to the project for MacOSX users?

2023-05-18 16:58 UTC, closed without merging