add all sigma rules for security analytics
opensearch-project/security-analytics pull request #26
Opened 2022-08-16 22:08 UTC by sbcd90

Signed-off-by: Subhobrata Dey <sbcd90@gmail.com>

### Description
this PR adds all pre-packaged sigma rules into the security-analytics repo.

### Issues Resolved
[Rule ingestion layer](https://github.com/opensearch-project/security-analytics/issues/5)
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [X] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-16 22:20 UTC, getsaurabh02 requested changes
Thanks @sbcd90. I am wondering how are we going to categorize these rules and map them   with the log type, so that we can associate detectors with the right set of rules. 

I see one of the possible approaches as we pre-bucketize these rules into specific paths, based on the log types they are useful for, and then we and a mapping file which maps the Rule Paths (folder/subfolder/specific-rule) to the 8 log groups that we will support initially. 

As we will add new log group type, we can add more rules and update the mapping. Let me know if you concur with the thought or have any alternative proposal.

2022-08-16 22:20 UTC, getsaurabh02 commented on src/main/resources/OSMapping/fieldmappings.yml
> +    fieldA1: mappedA
Looks like some mapping template. Can we add comments to suggest this is a reference template for new templates to be added in future.

2022-08-17 02:01 UTC, sbcd90 commented on src/main/resources/OSMapping/fieldmappings.yml
> +    fieldA1: mappedA
fixed it & added comments to yaml files.

2022-08-17 20:07 UTC, getsaurabh02 requested changes

2022-08-17 20:11 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
> +            InputStream is = this.getClass().getClassLoader().getResourceAsStream("OSMapping/windows/fieldmappings.yml");
@getsaurabh02 this will be made dynamic in the 3rd pr. the static mapping is kept here just for test cases to pass for this pr.

2022-08-18 17:27 UTC, getsaurabh02 approved these changes

2022-09-13 02:24 UTC, eirsep approved these changes

2022-09-13 04:16 UTC, merged