Model2 Approach to a Unified Common-Utils
opensearch-project/security-analytics pull request #29
Opened 2022-08-24 19:50 UTC by okram

This is related to ISSUE-10 of security analytics. It's the best push I have that uses a simpler Model infrastructure based on public fields and reflection. It also incorporates the notion of redirecting existing actions to a intermediate "translator action" (@getsaurabh02 idea). 

This is a 3 part PR across common-utils, alerting, and security analytics. All under the same `model2/` branch.

*CheckList:*
[X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-24 20:11 UTC, okram commented
Here is a script that I wrote that will build the `opensearch-alerting-2.2.0-SNAPSHOT.zip`. The build order is important for these 3 repos. You have to do: `common-utils/`, then `alerting/`, then `security-analytics/`. Between each, make sure your local `.m2` Maven repo has the previously build `SNAPSHOT` or else you'll pull it from remote. And before you do `security-analytics/`, you have to copy over (and rename `.zip`) the `alerting/` jar.

Because of the MacOSX build via Docker, there are some `.m2/` antics that shouldn't be necessary via a pure Linux build.

```
#!/bin/bash

mkdir /docker/tmp/.m2
mkdir /docker/tmp/.m2/repository
mkdir /docker/tmp/.m2/repository/org/
pwd; pushd common-utils
gradle build publishToMavenLocal --info; popd
cp -rf ~/.m2/repository/org/opensearch/ /docker/tmp/.m2/repository/org/
pwd; pushd alerting
gradle test publishPluginZipPublicationToMavenLocal --info; popd
cp ~/.m2/repository/org/opensearch/opensearch-alerting/2.2.0.0-SNAPSHOT/opensearch-alerting-2.2.0.0-SNAPSHOT.jar security-analytics/src/test/resources/alerting/opensearch-alerting-2.2.0.0.zip
cp -rf ~/.m2/repository/org/opensearch/ /docker/tmp/.m2/repository/org/
pwd; pushd security-analytics
gradle build --info; popd
```

2022-08-25 01:32 UTC, getsaurabh02 requested changes

2022-08-25 01:32 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/alerting/resthandlers/RestIndexMonitorAction.java
> +            final Monitor monitor = ModelSerializer.read(parser, Monitor.class);*/
nit:cleanup ?

2022-08-25 01:32 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/alerting/resthandlers/RestIndexMonitorAction.java
> +                    new IndexMonitorRequest(monitorId, 3L, 4L, WriteRequest.RefreshPolicy.IMMEDIATE, request.method(), new Monitor("anid","atype",12L,"hello",235L,"seconds",List.of())),
Looks like a test code. Why aren't we constructing the transport fields from the rest requests

2022-08-25 01:32 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/alerting/transport/TransportExecuteMonitorAction.java
> +            actionListener.onResponse(new ExecuteMonitorResponse(new Monitor("dsaf", "Atype", 135L, "nae", 245L, "asdf", List.of())));
Is this test code again?

2022-08-25 01:32 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/alerting/ExampleAlertingJSON.java
> +public class ExampleAlertingJSON {
What is the use of this?

2022-08-25 01:32 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/alerting/ExampleIndexMonitorJSON.java
> +    public static String exampleIndexMonitor = "{\n" +
Let's define these as resources (resource json files) instead?

2022-08-25 01:32 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/alerting/resthandlers/RestExecuteMonitorAction.java
> +public class RestExecuteMonitorAction extends BaseRestHandler {
Java docs across will be useful

2022-11-09 06:26 UTC, closed without merging