initial commit
opensearch-project/security-analytics pull request #30
Opened 2022-09-01 22:04 UTC by petardz

Signed-off-by: Petar Dzepina <petar.dzepina@gmail.com>

### Description
Implementation of UpdateIndexMappingsAction
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-02 01:26 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String MAPPER_BASE_URI = SAP_BASE_URI + "/mapper";
hi @petardz, can you please change the `uri` path to `/_plugins/_security_analytics/mappings` or something similar? check here: https://github.com/sbcd90/security-analytics/blob/alerting_integ/src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java#L41

2022-09-02 01:26 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        indicesClient.putMapping(request);
this calls the `synchronous` api & it is not recommended as it blocks the `Transport Action` thread. Can you make it asynchronous? check here: https://github.com/sbcd90/security-analytics/blob/alerting_integ/src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java#L309-#L336
& 
here
https://github.com/sbcd90/security-analytics/blob/alerting_integ/src/main/java/org/opensearch/securityanalytics/mappings/MapperApplier.java#L24-#L29

2022-09-02 01:26 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/action/mapping/TransportUpdateIndexMappingsAction.java
> +public class TransportUpdateIndexMappingsAction extends TransportClusterManagerNodeAction<UpdateIndexMappingsRequest, AcknowledgedResponse> {
is it needed to extend from `TransportClusterManagerNodeAction`? is `HandledTransportAction` not sufficient? check here:
https://github.com/sbcd90/security-analytics/blob/alerting_integ/src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java#L66

2022-09-02 01:26 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
> +        assertEquals(HttpStatus.SC_OK, response.getStatusLine().getStatusCode());
can you also add `assert` statements for mapping applied? e.g.
```
Assert.assertTrue(((Map<String, Object>) response.getMappings().get("network").getSourceAsMap().get("properties")).containsKey("source"));
```

2022-09-02 01:27 UTC, sbcd90 commented
hi @petardz , thanks a lot for the pr. i have a few comments. can you kindly look into them?

2022-09-05 16:56 UTC, sbcd90 reviewed
please also update your class files with license headers.

2022-09-05 16:56 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +}
can we also create similar transport requests for `read` & `update` mappings?

2022-09-05 16:57 UTC, sbcd90 commented
hi @petardz , thanks a lot for the pr. i have a few comments. can you kindly look into them?

2022-09-06 16:40 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +}
done

2022-09-06 16:40 UTC, petardz commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
> +        assertEquals(HttpStatus.SC_OK, response.getStatusLine().getStatusCode());
done

2022-09-06 16:40 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        indicesClient.putMapping(request);
done

2022-09-06 16:41 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +    public static final String MAPPER_BASE_URI = SAP_BASE_URI + "/mapper";
renamed it to _security_analytics

2022-09-06 17:41 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/action/mapping/TransportUpdateIndexMappingsAction.java
> +public class TransportUpdateIndexMappingsAction extends TransportClusterManagerNodeAction<UpdateIndexMappingsRequest, AcknowledgedResponse> {
changed it to extend HandledTransportAction

2022-09-07 17:00 UTC, petardz commented
> please also update your class files with license headers.

done

2022-09-07 19:30 UTC, sbcd90 commented
@petardz Can you please also write unit tests for `request` & `response` classes?
check here: https://github.com/opensearch-project/alerting/blob/main/alerting/src/test/kotlin/org/opensearch/alerting/action/AcknowledgeAlertRequestTests.kt
&
https://github.com/opensearch-project/alerting/blob/main/alerting/src/test/kotlin/org/opensearch/alerting/action/AcknowledgeAlertResponseTests.kt

2022-09-07 21:49 UTC, getsaurabh02 requested changes
Thanks @petardz. Overall looks good. Few changes/suggestions requested.

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        );
nit: new line.

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    public void updateMappingAction(String logIndex, String field, String alias) throws IOException {
Is this method intended to update a single field? I dont see the usage yet.

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        PutMappingRequest request = new PutMappingRequest(logIndex).source(field, alias);
What happens if the provided field is non-existent, due to a recent update.

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    public ImmutableOpenMap<String, MappingMetadata> readMappingAction(String logIndex) throws ExecutionException, InterruptedException {
should we call it ``getMappingAction`` instead?

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperFacade.java
> +        }
do we intent to make it singleton? If yes shall we move it to a private constructor instead?

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/action/mapping/TransportUpdateIndexMappingsAction.java
> +                    request.alias,
Is this parameter for the index alias?

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/action/mapping/GetIndexMappingsRequest.java
> +package org.opensearch.securityanalytics.mapper.action.mapping;
Lets create another package ```mapper.models``` for request/response objects

2022-09-07 21:49 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
> +    public void testCreateMappingSuccess() throws IOException {
Lets add tests related to few other failure scenarios:
1. "path" not present
2. Multiple alias with the same name.
3. Multiple alias for the same path (positive case).

2022-09-07 21:49 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
> +    public void testUpdateAndGetMappingSuccess() throws IOException {
Lets add test to verify the older mapping (customer provided) continues to stay.

2022-09-07 21:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/resthandler/RestUpdateIndexMappingsAction.java
> +public class RestUpdateIndexMappingsAction extends BaseRestHandler {
We will also need ``DeleteIndexMappingAction`` which can remove selective aliases as present in the json file. 
I am inclined towards doing it as a separate change in a follow-up PR

2022-09-07 21:59 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/resthandler/RestCreateIndexMappingsAction.java
> +public class RestCreateIndexMappingsAction extends BaseRestHandler {
Wondering if we need Rest APIs here for end user? Transport APIs will be used in the detector create/update flow.

2022-09-08 15:12 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        PutMappingRequest request = new PutMappingRequest(logIndex).source(field, alias);
error would be thrown

2022-09-08 15:20 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    public void updateMappingAction(String logIndex, String field, String alias) throws IOException {
I agree. This should be at least changed to:

2022-09-09 22:38 UTC, petardz commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperIT.java
> +    public void testUpdateAndGetMappingSuccess() throws IOException {
done

2022-09-09 22:38 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/action/mapping/GetIndexMappingsRequest.java
> +package org.opensearch.securityanalytics.mapper.action.mapping;
done

2022-09-09 22:39 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperFacade.java
> +        }
made it singleton

2022-09-09 22:39 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    public ImmutableOpenMap<String, MappingMetadata> readMappingAction(String logIndex) throws ExecutionException, InterruptedException {
renamed

2022-09-13 00:41 UTC, getsaurabh02 reviewed
Thanks @petardz . Overall looks good to me.

2022-09-13 00:41 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    }
why do we need this?

2022-09-13 00:41 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +public class MappingsTraverser {
Can we please document the behavior in java doc to set the expectation.

2022-09-13 00:41 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperApplierTests.java
> +import static org.mockito.Mockito.*;
Lets avoid * imports

2022-09-13 19:16 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +    }
deleted

2022-09-13 19:16 UTC, petardz commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperApplierTests.java
> +import static org.mockito.Mockito.*;
replaced * imports

2022-09-13 19:16 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +public class MappingsTraverser {
added javadocs

2022-09-13 21:43 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperFacade.java
> +        mapperMap.put("netflow", "OSMapping/NetFlowMapping.json");
we should define this mapping as a static map or via one of the yml in the resource once we add more log types. Something to note for the follow up PRs

2022-09-13 21:43 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +import java.util.*;
multiple imports. Applicable at multiple places.

2022-09-13 21:43 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +public class MappingsTraverser {
Lets add a corresponding unit test for this class.

2022-09-13 21:43 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperUtils.java
> +public class MapperUtils {
We should have a dedicated UTs for the utils method

2022-09-13 21:43 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/mapper/resthandler/RestGetIndexMappingsAction.java
> +public class RestGetIndexMappingsAction extends BaseRestHandler {
Should this API only return alias mapping which are particularly applied for the SA config? We already have a Get Mapping API. I think this should be specific to SA. Thoughts?
We can open an issue, discuss and address this behavior as a follow up PR. Doesn't seem to be a current blocker.

2022-09-13 21:43 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/ClientUtils.java
> +public class ClientUtils extends OpenSearchRestTestCase {
nit: should we name it SecurityAnalyticsClientUtils ?

2022-09-13 21:43 UTC, getsaurabh02 commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperApplierTests.java
> +    public void testMultipleAliasesWithSameName() throws IOException {
Test missing field for the aliases as well?

2022-09-13 23:25 UTC, petardz commented on src/test/java/org/opensearch/securityanalytics/mapper/MapperApplierTests.java
> +    public void testMultipleAliasesWithSameName() throws IOException {
_testPathIsNull_ test is testing that, if I understood you correctly

2022-09-13 23:25 UTC, petardz commented on src/test/java/org/opensearch/securityanalytics/ClientUtils.java
> +public class ClientUtils extends OpenSearchRestTestCase {
done

2022-09-13 23:25 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperUtils.java
> +public class MapperUtils {
done

2022-09-13 23:25 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +public class MappingsTraverser {
done

2022-09-13 23:25 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
> +import java.util.*;
done

2022-09-14 05:31 UTC, getsaurabh02 approved these changes

2022-09-15 22:15 UTC, sbcd90 approved these changes

2022-09-15 22:15 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperApplier.java
> +        );
Can we remove this method? because it looks like it is not used.

2022-09-15 22:15 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperUtils.java
> +        MappingsTraverser mappingsTraverser = new MappingsTraverser(mappingMetadata);
can we make the methods of static so that we dont create an object everytime?

2022-09-15 22:15 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperFacade.java
> +        mapperMap.put("netflow", "OSMapping/NetFlowMapping.json");
can we fix this before merging?

2022-09-16 00:52 UTC, merged