adds create detector api flow
opensearch-project/security-analytics pull request #32
Opened 2022-09-10 01:41 UTC by sbcd90

Signed-off-by: Subhobrata Dey <sbcd90@gmail.com>

### Description
adds create detector api flow
 
### Check List
- [X] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-14 21:21 UTC, eirsep commented
I have a concern i wanted to call out with regards to the use of index document models in request layer which i have noticed in both Alerting, SAP i.e. usage of Detector in IndexDetectorRequest..

this doesnt seem to be a right practive.. 

I feel it would be better to have a Detector DTO at rest layer which should be used to build or which can be built from Detector document stored in the index.

This ensures fields of detector which dont need to be exposed are abstracted away from rest responses and transport level responses(if required)

@getsaurabh02 @sbcd90 what are your thoughts on this.

2022-09-14 21:53 UTC, eirsep requested changes
Thanks for these changes Subho

i have some initial comments reg. structuring which I would like to discuss to understand best practices which we can address right away as we are writing new logic

2022-09-14 21:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
> +        public String getDetectorType() throws IOException {
Enum allows properties which is neater and avoids switch case by implicit and mandatory declaration and mainly avoids unnecessary Exception handling.

```
public enum DetectorType {
        APPLICATION("application"),
        APT("apt"),
        CLOUD("cloud"),
        COMPLIANCE("compliance"),
        LINUX("linux"),
        MACOS("macos"),
        NETWORK("network"),
        PROXY("proxy"),
        WEB("web"),
        WINDOWS("windows");

        public String getDetectorType() {
            return type;
        }

        private String type;

        DetectorType(String type) {
            this.type = type;
        }
    }
```

2022-09-14 21:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
> +                        throw new IllegalStateException("Monitor type should be one of ");
plz add list of detector types

2022-09-14 21:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
> +                        throw new IllegalStateException("Monitor type should be one of ");
illegalArgumentException would be more suited here?

2022-09-14 21:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/IndexDetectorRequest.java
> +            RestRequest.Method method,
don't think its right to use RestRequest.Method here. This object should be limited to rest layer if possible. 

maybe just use some enum Action{CREATE, UPDATE} or a boolean create

2022-09-14 21:53 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/IndexDetectorAction.java
> +public class IndexDetectorAction extends ActionType<IndexDetectorResponse> {
Is this a practice followed in opensearch?

can we have CreateDetectorAction and UpdateDetectorAction and corresponding request, response, transport and rest layer?

2022-09-15 17:37 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
> +                        throw new IllegalStateException("Monitor type should be one of ");
fixed it.

2022-09-15 17:37 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
> +        public String getDetectorType() throws IOException {
fixed it.

2022-09-15 19:10 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/action/IndexDetectorResponse.java
> +            .field(Detector.ALERTING_MONITOR_ID, detector.getMonitorId())
looks much cleaner, thanks.

2022-09-15 19:10 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +public class DetectorMonitorConfig {
These changes looks to be coming from a different PR. Are we merging these as well?

2022-09-15 19:19 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/config/monitors/DetectorMonitorConfig.java
> +public class DetectorMonitorConfig {
yes. they are part of the commit from @eirsep . https://github.com/opensearch-project/security-analytics/pull/32/commits/69f70a48e81b0ce2f89f0ad1dc2243cc6b5f79a
this is needed in the pr because otherwise our integration tests will fail.  https://github.com/opensearch-project/security-analytics/blob/3618a2056fee66e30daae1cb47bfa2dae720ea5f/src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java#L25-#L52

2022-09-16 17:35 UTC, getsaurabh02 submitted a review, later dismissed

2022-09-16 20:41 UTC, getsaurabh02 approved these changes
Thanks @sbcd90 Lets add the list of independent PRs we are trying to merge here in the description.

2022-09-16 23:25 UTC, eirsep approved these changes

2022-09-16 23:29 UTC, merged