Mapper Actions improvements
opensearch-project/security-analytics pull request #35
Opened 2022-09-18 13:37 UTC by petardz

### Description
Extended capability of CreateMappingAction to allow partial mapping apply, in case index mappings are missing some of the alias mappings. This is controlled by request boolean property **_partial_**

Reworked GetMappingAction to return only alias mappings which are applied previously by Create/Update Mapping Actions.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-20 23:40 UTC, getsaurabh02 requested changes
Thanks @petardz LGTM, few comments to address.

2022-09-22 20:58 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/action/GetIndexMappingsRequest.java
> +            xcp.nextToken();
For some reason I had to do this. currentToken was returning null.

2022-09-22 21:25 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MapperFacade.java
> +    private static final Logger log = LogManager.getLogger(RestIndexDetectorAction.class);
done

2022-09-23 00:01 UTC, getsaurabh02 approved these changes

2022-09-23 00:01 UTC, getsaurabh02 commented
Tests need fix @petardz

2022-09-27 19:48 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/mapper/MappingsTraverser.java
>      public MappingsTraverser(String mappings, Set<String> typesToSkip) throws IOException {
added more javadocs

2022-09-29 21:46 UTC, getsaurabh02 approved these changes

2022-09-29 22:07 UTC, sbcd90 approved these changes

2022-09-29 22:49 UTC, merged