added RestGetFindingsAction
opensearch-project/security-analytics pull request #39
Opened 2022-09-21 20:47 UTC by petardz

Signed-off-by: Petar Dzepina <petar.dzepina@gmail.com>

### Description
Added RestGetFindingsAction. TransportGetFindingsAction of alerting plugin is called.

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-22 20:45 UTC, getsaurabh02 reviewed
Thanks @petardz We will need to wait until the common-utils changes are merged. 
Also, lets add the API request and response as part of the issue description.

2022-09-22 20:45 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java
> +public class RestGetFindingsAction extends BaseRestHandler {
Lets add java doc

2022-10-05 18:58 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java
> +    private Long version;
what is `version` field for? Can this be removed?

2022-10-05 19:09 UTC, eirsep requested changes
Thanks for this PR, @petardz 

Left a few comments on request fields and code structuring. but overall change looks good

2022-10-05 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +        findingsService = new FindingsService(client);
i dont think FindingsService is a component. This can be initiated in TransportGetFindingsAction

2022-10-05 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +                for(String monitorId : monitorIds) {
can you check and try use a GroupedActionListener construct

sample from my crude WIP PR: https://github.com/opensearch-project/security-analytics/blob/74b4c3e12bc36518b14724f80229276d681123e9/src/main/java/org/opensearch/securityanalytics/transport/TransportGetDetectorAlertsAction.java

2022-10-05 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +        Table table = new Table(
we need to accept Table params from API Request (as params maybe) 

let's reuse table logic from Alerting Plugin Get findings API

2022-10-05 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +                        listener.onFailure(e);
let's add log lines like log.error("Failed to fetch findings",e) and java docs

2022-10-05 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +        this.findingsService = findingsService;
can we initialize findings service here instead of injecting it. we do have Client injected here and looks like that's all is required by findings.

2022-10-05 19:48 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +                for(String monitorId : monitorIds) {
done

2022-10-05 20:10 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +        this.findingsService = findingsService;
done

2022-10-05 20:11 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/SecurityAnalyticsPlugin.java
> +        findingsService = new FindingsService(client);
done

2022-10-05 20:12 UTC, petardz commented on src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java
> +    private Long version;
done

2022-10-05 21:46 UTC, eirsep requested changes
lgtm except a minor comment

plz add tests

2022-10-05 21:46 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +                                new IllegalArgumentException("Failed to fetch findings for detector" + detectorId)
let's throw a 500 exception or a SAP wrapped exception here.

This is not illegal argument as user hasn't passed any illegal/incorrect argument.

Also can we verify how many have succeeded or failed instead. Since this is a list api if a few fail we can log errors and return the rest of the findings. what say..

2022-10-08 00:09 UTC, eirsep commented
Plz add licenses 
```
Files with unapproved licenses:

  /home/runner/work/security-analytics/security-analytics/src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
  /home/runner/work/security-analytics/security-analytics/src/test/java/org/opensearch/securityanalytics/findings/FindingServiceTests.java

2022-10-10 00:26 UTC, eirsep approved these changes

2022-10-10 07:04 UTC, sbcd90 approved these changes

2022-10-10 07:04 UTC, merged