transport layer for get detector and Integration tests
opensearch-project/security-analytics pull request #40
Opened 2022-09-27 17:17 UTC by raj-chak

Signed-off-by: Raj Chakravarthi <raj@icedome.ca>

### Description
This has the transport layer for get detector, resthandler for search detector ( transport pending) and integration tests for both get and search
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-27 20:42 UTC, eirsep requested changes

2022-09-27 20:42 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/GetDetectorResponse.java
> +                .field(Detector.ALERTING_MONITOR_ID, detector.getMonitorId())
we shouldn't expose monitor id in get detector response.

2022-09-27 20:42 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/GetDetectorResponse.java
> +                .field(Detector.ALERTING_MONITOR_ID, detector.getMonitorId())
@getsaurabh02 do we also need a bulk api like list detectors (keeping in mind dashboards)

2022-09-27 20:42 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
> +import org.apache.http.HttpEntity;
can we add GetDetectorResponseTests to test ser/deserialization.

2022-09-27 20:42 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
> +import org.apache.http.HttpEntity;
similar for request

2022-09-27 20:42 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
>  import static org.opensearch.securityanalytics.TestHelpers.*;
let's avoid wildcard (*) imports

2022-09-27 20:46 UTC, eirsep commented
@getsaurabh02 @sbcd90 

currently there is IndexDetectorResponse and GetDetectorResponse.

Should we instead have DetectorResponse and that DTO can be the response for Get Detector and reused as a nested field in IndexDetectorResponse as there is a lot of redundant code and will become an overhead as more changes are made to detectors

```
public class DetectorResponse{} // response for get detector

public class IndexDetectorResponse { // response for index detector
    DetectorResponse detectorResponse,
    RestStatus restStatus
    ...
    ...
}
```

2022-09-27 21:15 UTC, raj-chak commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
>  import static org.opensearch.securityanalytics.TestHelpers.*;
@sbcd90  I did a full sync and applied my changes to this branch, some of these comments may be on your changes

2022-09-27 21:18 UTC, raj-chak commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
> +import org.apache.http.HttpEntity;
yes I will remove org.json from testing as well

2022-09-28 02:05 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchDetectorAction.java
> +    static class RestSearchDetectorResponseListener extends RestResponseListener<SearchResponse> {
let's return List<DetectorResponse>

2022-09-29 23:02 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/action/GetDetectorResponse.java
> +                .field(Detector.ALERTING_MONITOR_ID, detector.getMonitorId())
Yes we will have additional API for ListDetectors

2022-09-29 23:12 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/model/Detector.java
>      private static final Logger log = LogManager.getLogger(Detector.class);
We could use Detector DTO as a common object for returning the GetDetector, IndexDetector and ListDetector responses for consistency of information being exposed via the APIs. This can provide the required parsing and stream conversion logic.

2022-09-30 02:30 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java
>  import static org.opensearch.securityanalytics.TestHelpers.*;
@raj-chak @eirsep this is fixed in https://github.com/opensearch-project/security-analytics/pull/43

2022-10-03 19:08 UTC, sbcd90 approved these changes

2022-10-03 19:08 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchDetectorAction.java
> +                log.error(hit.getSourceAsString());
can you review log.error messages?

2022-10-03 19:10 UTC, raj-chak commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchDetectorAction.java
> +                log.error(hit.getSourceAsString());
will remove it! forgot to remove it before commiting

2022-10-03 23:42 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetDetectorAction.java
> +                .version(request.getVersion());
User should not be expected to know version. "version" is a get document field and is not relevant here. Plz remove this field from request and response and use version only if its necessary

2022-10-04 17:19 UTC, raj-chak commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetDetectorAction.java
> +                .version(request.getVersion());
How about this line in 
src/main/java/org/opensearch/securityanalytics/resthandler/RestGetDetectorAction.java

GetDetectorRequest req = new GetDetectorRequest(detectorId, RestActions.parseVersion(request));

2022-10-04 18:29 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetDetectorAction.java
> +                .version(request.getVersion());
https://github.com/opensearch-project/security-analytics/issues/49

created an issue to track and addresss this overall. let's merge this PR now

approving.

2022-10-04 18:29 UTC, eirsep approved these changes

2022-10-04 19:05 UTC, sbcd90 approved these changes

2022-10-04 19:06 UTC, merged