adds delete detector flow
opensearch-project/security-analytics pull request #43
Opened 2022-09-28 02:28 UTC by sbcd90

Signed-off-by: Subhobrata Dey <sbcd90@gmail.com>

### Description
adds delete detector flow
 
### Issues Resolved
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-28 18:07 UTC, getsaurabh02 requested changes

2022-09-28 18:07 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +            deleteAlertingMonitor(monitorId, request.getRefreshPolicy(),
We should also clean up the rule documents which are associated with this detector

2022-09-28 18:07 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +                            deleteDetector(detector.getId(), request.getRefreshPolicy(),
Once the rule documents has been deleted, we could also delete the rule index for that log-type in case there are no other monitors have the rules for the same type.

2022-09-28 18:22 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +            deleteAlertingMonitor(monitorId, request.getRefreshPolicy(),
@getsaurabh02 this is taken care by monitor delete

2022-09-28 19:39 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +            deleteAlertingMonitor(monitorId, request.getRefreshPolicy(),
@sbcd90 we would need to add custom index support there also then.

2022-09-28 19:39 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +                            deleteDetector(detector.getId(), request.getRefreshPolicy(),
system indices shouldn't do that. might cause concurrency issues with some other detector trying to index document.

2022-09-28 19:55 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +            deleteAlertingMonitor(monitorId, request.getRefreshPolicy(),
@eirsep yes. we should do it

2022-09-29 23:58 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java
> +                            deleteDetector(detector.getId(), request.getRefreshPolicy(),
@getsaurabh02 added the logic https://github.com/opensearch-project/security-analytics/blob/f8ca0b5e58a4f389b76e999b90872dcd9028f8a2/src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteDetectorAction.java#L148
& updated test case. 
https://github.com/opensearch-project/security-analytics/blob/f8ca0b5e58a4f389b76e999b90872dcd9028f8a2/src/test/java/org/opensearch/securityanalytics/resthandler/DetectorRestApiIT.java#L73-#L74

2022-09-30 18:20 UTC, getsaurabh02 approved these changes

2022-09-30 18:28 UTC, eirsep approved these changes
Took a cursory look. Hope this logic has been tested thoroughly. Rest LGTM

2022-09-30 18:29 UTC, merged