Gradle update
opensearch-project/security-analytics pull request #437
Opened 2023-05-16 11:23 UTC by petardz

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-02 18:06 UTC, sbcd90 approved these changes

2023-06-02 20:43 UTC, eirsep submitted a review, later dismissed

2023-06-02 20:44 UTC, eirsep commented on build.gradle
> +        requires('elasticsearch-oss', versions.elasticsearch, EQUAL)
why aer we changing this?

2023-06-02 20:44 UTC, eirsep commented on build.gradle
> +        maintainer 'OpenDistro for Elasticsearch Team <opendistro@amazon.com>'
why are we changing this?

2023-06-02 20:46 UTC, petardz commented on build.gradle
> +        maintainer 'OpenDistro for Elasticsearch Team <opendistro@amazon.com>'
this was copied over from ISM. Let me revert i

2023-06-02 20:53 UTC, petardz commented on build.gradle
> +        maintainer 'OpenDistro for Elasticsearch Team <opendistro@amazon.com>'
reverted

2023-06-02 20:53 UTC, petardz commented on build.gradle
> +        requires('elasticsearch-oss', versions.elasticsearch, EQUAL)
reverted

2023-06-06 21:34 UTC, AWSHurneyt approved these changes

2023-06-07 18:13 UTC, sbcd90 requested changes

2023-06-07 18:13 UTC, sbcd90 commented on build.gradle
> +        version = "${project.version}" - "-SNAPSHOT"
why do we need to change this?

2023-06-07 18:19 UTC, petardz commented on build.gradle
> +        version = "${project.version}" - "-SNAPSHOT"
reverted this change

2023-06-07 18:26 UTC, sbcd90 approved these changes

2023-06-07 18:27 UTC, merged