Rule editor
opensearch-project/security-analytics pull request #52
Opened 2022-10-05 07:02 UTC by sbcd90

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-13 23:23 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/DeleteRuleRequest.java
> +        this.forced = forced;
plz add Javadocs for req, res and important fields

2022-10-14 00:22 UTC, eirsep requested changes

2022-10-14 00:22 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java
> +                                onFailures(new OpenSearchStatusException(String.format(Locale.getDefault(), "Rule with id %s is actively used by detectors. Update can be forced by setting forced flag
we can to create a wrapper SecurityAnalyticsException

2022-10-14 00:22 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
> +            if (folderPath.endsWith(Detector.DetectorType.APPLICATION.getDetectorType())) {
NIT: if we know folder path pattern can we split on separator and extract the detector type value and just put log path. This if/else if is not mantainable and seems unnecessary

2022-10-14 00:22 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -        String index = createTestIndex(randomIndex(), windowsIndexMapping());
can we instead see if a small change can fix this ?

2022-10-14 22:05 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java
> +    private String category;
yes rule category == log type

2022-10-14 22:08 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
> +                List<DetectorRule> rules = detector.getInputs().get(0).getRules();
when we allow all elements we go in the direction of supporting multiple log types per detector. As we dont support the scenario in `create/update detector` flow yet, i did not add support for it in `delete detector flow`. 
will look into it next week & create a pr for it once this is merged.

2022-10-14 22:10 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java
> +    private String category;
will add javadoc

2022-10-14 22:11 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java
> +                                onFailures(new OpenSearchStatusException(String.format(Locale.getDefault(), "Rule with id %s is actively used by detectors. Update can be forced by setting forced flag
yes we use a wrapper. `OpenSearchStatusException` to correctly construct the exception body.
https://github.com/opensearch-project/security-analytics/blob/57b74c67b537ae0f40de72cc6a8a3e6806d9c427/src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java#L325-#L329

2022-10-14 22:12 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
> +            if (folderPath.endsWith(Detector.DetectorType.APPLICATION.getDetectorType())) {
yes wanted to look into this piece of code. will work on it.

2022-10-14 22:14 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/DeleteRuleRequest.java
> +public class DeleteRuleRequest extends ActionRequest {
We may support deletion of multiple rules in future. will create an issue for it. the HTTP DELETE request only allows deletion of a specified resource. https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

2022-10-15 01:55 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -        String index = createTestIndex(randomIndex(), windowsIndexMapping());
fixed it.

2022-10-15 01:55 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/util/RuleIndices.java
> +            if (folderPath.endsWith(Detector.DetectorType.APPLICATION.getDetectorType())) {
fixed it.

2022-10-15 01:55 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/findings/FindingsService.java
> +/*        org.opensearch.commons.alerting.action.GetFindingsRequest req =
fixed it.

2022-10-15 01:55 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexRuleAction.java
> +        if (category == null) {
fixed it.

2022-10-15 01:57 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/DeleteRuleRequest.java
> +        this.forced = forced;
fixed it.

2022-10-15 01:57 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java
> +    private String category;
fixed it.

2022-10-17 08:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/action/DeleteRuleRequest.java
> +public class DeleteRuleRequest extends ActionRequest {
lets create a tracking issue, since internally deleting a monitor will require a case where all the rules for that monitor (or log type) are deleted at once (and consistently).

2022-10-17 08:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java
> +    private String category;
Lets keep the naming consistent ?

2022-10-17 08:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexRuleAction.java
> +        return channel -> client.execute(IndexRuleAction.INSTANCE, ruleRequest, indexRuleResponse(channel, request.method()));
How are we planning to dedupe the rules in the rule index, while they are being imported from the pre-canned resources? 
Should by having the rule-id as document id handle this? This way we have always one copy of the pre-canned rules available for view or import into monitors.

2022-10-17 08:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestSearchRuleAction.java
> +public class RestSearchRuleAction extends BaseRestHandler {
Is it rally a Search or Get instead?

2022-10-17 08:49 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteRuleAction.java
> +public class TransportDeleteRuleAction extends HandledTransportAction<DeleteRuleRequest, DeleteRuleResponse> {
We should create another transport action for multi-delete which could abstract this, and orchestrate logical deletion of multiple associated rules

2022-10-17 21:14 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/action/IndexRuleRequest.java
> +    private String category;
fixed it.

2022-10-17 21:15 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestIndexRuleAction.java
> +        return channel -> client.execute(IndexRuleAction.INSTANCE, ruleRequest, indexRuleResponse(channel, request.method()));
As per our discussions, pre-packaged rules are never created. Hence, there are no chances of duplication.

2022-10-17 22:47 UTC, eirsep approved these changes

2022-10-18 01:34 UTC, getsaurabh02 approved these changes

2022-10-18 01:35 UTC, merged