add field based rules support in correlation engine
opensearch-project/security-analytics pull request #737
Opened 2023-11-28 04:30 UTC by sbcd90

### Description
add field based rules support in correlation engine
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-29 18:41 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                onAutoCorrelations(detector, finding, Map.of());
this method seems to be search on correlation index

if auto-correlation  is disabled why are we invoking this method?

2023-11-29 20:36 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                onAutoCorrelations(detector, finding, Map.of());
this is the callback when auto correlations complete. so, if auto-correlations are disabled, we directly call the callback without generating auto correlations.

2023-11-29 21:40 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                    for (Triple<CorrelationRule, SearchHit[], String> rule: filteredCorrelationRules) {
nit: why are we not creating pojos. we have increased from list to triple?

2023-11-29 22:55 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.enable_auto_correlations",
rename this to `plugins.security_analytics.auto_correlations_enabled`

2023-11-29 22:55 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            false,
why is auto correlations disabled by default?

2023-11-29 22:59 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/TestHelpers.java
> +    public static String randomRuleForCorrelations(String value) {
nit: rename to randomCloudtrailRuleForCorrelations

2023-11-29 23:00 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/TestHelpers.java
> +    public static String randomRuleForCorrelations(String value) {
nit: rename to `randomCloudtrailRuleForCorrelations`

2023-11-29 23:04 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
> +    public void testBasicCorrelationEngineWorkflowWithFieldBasedRulesOnMultipleLogTypes() throws IOException, InterruptedException {
do we support correlation for custom log types?

if yes, can we add a tests for correlation on (custom log types + log types)

2023-11-29 23:04 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
> +                    Assert.assertTrue(true);
why are we not validating field values like finding id or field name etc.

2023-11-29 23:09 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -    @Ignore
why did we uncomment
is this test flakiness fixed?

2023-11-29 23:12 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
why is JoinEngine not a "component" injected from `createComponents()` in Plugin definition? We shouldn't have to parse a setting in transport action and pass it to correlation engine

2023-11-29 23:13 UTC, eirsep requested changes

2023-11-29 23:13 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
why is JoinEngine not a "component" injected from `createComponents()` in Plugin definition? We shouldn't have to parse a setting in transport action and pass it to correlation engine

2023-11-30 02:50 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                    for (Triple<CorrelationRule, SearchHit[], String> rule: filteredCorrelationRules) {
fixed it.

2023-11-30 02:51 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            "plugins.security_analytics.enable_auto_correlations",
fixed it.

2023-11-30 02:52 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/settings/SecurityAnalyticsSettings.java
> +            false,
auto correlations are disabled because they may generate too many irrelevant correlations. we're trying to further filter down auto correlations so that meaningful results are shown.

2023-11-30 02:52 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/TestHelpers.java
> +    public static String randomRuleForCorrelations(String value) {
fixed it.

2023-11-30 02:52 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
> +    public void testBasicCorrelationEngineWorkflowWithFieldBasedRulesOnMultipleLogTypes() throws IOException, InterruptedException {
added an integ test for it.

2023-11-30 02:54 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/correlation/CorrelationEngineRestApiIT.java
> +                    Assert.assertTrue(true);
we do not need to in this test as only `1 result` is expected. `0 correlations` mean error.

2023-11-30 02:56 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> -    @Ignore
flakiness was fixed by adding this https://github.com/opensearch-project/security-analytics/pull/737/files#diff-20d6f1670be34a4f479880ddef06426f6dc20ff28a153a9225e829eaa325a7f7

2023-11-30 06:56 UTC, eirsep submitted a review, later dismissed

2023-12-06 00:15 UTC, praveensameneni approved these changes

2023-12-06 00:15 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +import org.apache.commons.lang3.tuple.Triple;
is this import used at all?

2023-12-06 00:29 UTC, eirsep commented on src/main/resources/mappings/finding_mapping.json
> +        "fields": {
do we support multiple fields?

2023-12-06 01:09 UTC, merged