Allow deletion of custom log type if custom rule index is missing
opensearch-project/security-analytics pull request #767
Opened 2023-12-04 21:02 UTC by goyamegh

### Description
In the case when the detector index is present, but the custom rule index is missing, we want to allow the deletion of custom log types to be successful instead of throwing an error.
 
### Issues Resolved
#700 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-04 22:32 UTC, eirsep requested changes

2023-12-04 22:32 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
> +                                if (e instanceof IndexNotFoundException) {
can we do. an `index exists` check instead of letting this fail and handling exception.

2023-12-04 22:32 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
> +                public void onFailure(Exception e) {
log exception with custom message

2023-12-04 22:32 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
> +            log.error(String.format(Locale.ROOT, "Failed to delete log type"));
can we also log the name of the log type

2023-12-06 22:10 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
> +                                if (e instanceof IndexNotFoundException) {
Thanks for the suggestion. Added the check but still keeping the exception check to account for edge cases.

2023-12-06 22:11 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java
> +            log.error(String.format(Locale.ROOT, "Failed to delete log type"));
The exception being passed would ideally have the log type. Added the stack trace to be logged here as well.

2023-12-07 19:47 UTC, eirsep commented
Looks like delete log type is wrongly wired.

If detector index does NOT exist, we seem to directly delete the log type instead of checking if there is a rule index. 

https://github.com/opensearch-project/security-analytics/blob/8be2159f8913082f018b25af55ae10b54fb55cd7/src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java#L176

https://github.com/opensearch-project/security-analytics/blob/8be2159f8913082f018b25af55ae10b54fb55cd7/src/main/java/org/opensearch/securityanalytics/transport/TransportDeleteCustomLogTypeAction.java#L227-L229

Plz add check for rule index here also. extract into a method if redundant.

2023-12-07 19:52 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
> +    public void testDeleteCustomLogTypeWithRuleIndexMissing() throws IOException {
can you add two scenarios:
1. custom rules index exists, detector index exists.
2. custom rules index exists, detector index does not exist.

2023-12-08 21:33 UTC, eirsep approved these changes

2023-12-08 22:37 UTC, merged

2023-12-08 23:15 UTC, goyamegh commented on src/test/java/org/opensearch/securityanalytics/resthandler/CustomLogTypeRestApiIT.java
> +    public void testDeleteCustomLogTypeWithRuleIndexMissing() throws IOException {
Added.