support object fields in aggregation based sigma rules
opensearch-project/security-analytics pull request #789
Opened 2023-12-19 03:30 UTC by sbcd90

### Description
support object fields in aggregation based sigma rules.
e.g.
```
id: 25b9c01c-350d-4b95-bed1-836d04a4f324
title: test
description: Detects when an user creates or invokes a lambda function.
status: experimental
author: test
date: 2023/12/07
modified: 2023/12/07
logsource:
  category: cloudtrail
level: low
detection:
  condition: selection1 or selection2 | count(api.operation) by cloud.region > 1
  selection1:
    api.service.name:
      - lambda.amazonaws.com
    api.operation:
      - CreateFunction
  selection2:
    api.service.name:
      - lambda.amazonaws.com
    api.operation:      
      - Invoke
  timeframe: 20m
  tags:
    - attack.privilege_escalation
    - attack.t1078
```
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-20 07:00 UTC, eirsep commented on src/main/grammars/Aggregation.g4
> +IDENTIFIER : [a-zA-Z*_.][a-zA-Z_0-9.]* ;
will this work for `nested` type fields also?

2023-12-20 07:00 UTC, eirsep commented on src/main/generated/org/opensearch/securityanalytics/rules/condition/aggregation/AggregationLexer.java
> +        "\u0000\u0004\u0001\u000009\u0005\u0000**..AZ__az\u0005\u0000..09AZ__a"+
what are these changes?

2023-12-20 07:28 UTC, eirsep requested changes

2023-12-20 07:28 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +            fmtAggQuery = String.format(Locale.getDefault(), aggQuery, "result_agg", aggregation.getGroupByField(), aggregation.getAggField().replace(".", "_"), aggregation.getAggFunction().equals("c
why have we changed from `aggregation.getAggFunction()` to `aggregation.getAggFunction().equals("count")? "value_count": aggregation.getAggFunction()`?
Is this intentional?

2023-12-20 07:28 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +            fmtBucketTriggerQuery = String.format(Locale.getDefault(), bucketTriggerQuery, aggregation.getAggField().replace(".", "_"), aggregation.getAggField(), "result_agg", aggregation.getAggFiel
plz do `aggregation.getAggField().replace(".", "_")` **only once** and store in variable and re-use everywhere else

2023-12-20 07:28 UTC, eirsep commented on src/test/java/org/opensearch/securityanalytics/TestHelpers.java
> +    public static String randomCloudtrailOcsfDoc() {
can you create a document with object type fields in `a.b.c` (dot) format and test the same agg rule?

2023-12-20 07:28 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +        if (aggregation.getAggFunction().equals("count") && aggregation.getAggField().equals("*")) {
is there any edge case where field mappings need to be considered during aggregation rule parsing?

what if customer creates an aggregation rule with ECS field name?

can you add a test case where customer use ecs field name in rule and automatically mapped raw field name in index mapping

2024-01-13 09:22 UTC, sbcd90 commented on src/main/grammars/Aggregation.g4
> +IDENTIFIER : [a-zA-Z*_.][a-zA-Z_0-9.]* ;
`nested` fields cannot be queried using `query string queries`.

2024-01-13 09:25 UTC, sbcd90 commented on src/main/generated/org/opensearch/securityanalytics/rules/condition/aggregation/AggregationLexer.java
> +        "\u0000\u0004\u0001\u000009\u0005\u0000**..AZ__az\u0005\u0000..09AZ__a"+
these are generated code by antlr.

2024-01-13 09:26 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +            fmtAggQuery = String.format(Locale.getDefault(), aggQuery, "result_agg", aggregation.getGroupByField(), aggregation.getAggField().replace(".", "_"), aggregation.getAggFunction().equals("c
we want to support `count(field)`. earlier, we only supported `count(*)`.

2024-01-13 09:26 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +            fmtBucketTriggerQuery = String.format(Locale.getDefault(), bucketTriggerQuery, aggregation.getAggField().replace(".", "_"), aggregation.getAggField(), "result_agg", aggregation.getAggFiel
fixed it.

2024-01-13 09:28 UTC, sbcd90 commented on src/test/java/org/opensearch/securityanalytics/TestHelpers.java
> +    public static String randomCloudtrailOcsfDoc() {
ok updated the mapping to an object field. https://github.com/opensearch-project/security-analytics/pull/789/files#diff-32ce4f632f4dca5253d801824d6ac90e9fa458a73bf21a2a04f57750f98fd5c4R983

2024-01-13 09:30 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +        if (aggregation.getAggFunction().equals("count") && aggregation.getAggField().equals("*")) {
added an aggregation rule which leverages `raw->ecs mapping`.

2024-01-14 22:40 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/rules/backend/OSQueryBackend.java
> +            fmtAggQuery = String.format(Locale.getDefault(), aggQuery, "result_agg", aggregation.getGroupByField(), aggregation.getAggField().replace(".", "_"), aggregation.getAggFunction().equals("c
plz update description of PR to call this out.

2024-01-16 20:17 UTC, eirsep approved these changes

2024-01-16 22:42 UTC, merged