Customrule field validation
opensearch-project/security-analytics pull request #80
Opened 2022-10-26 18:03 UTC by petardz

### Description
Added rule validation during IndexRule Action. Rule fields are matched against rule category index's mappings.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-29 03:22 UTC, getsaurabh02 requested changes

2022-10-29 03:22 UTC, getsaurabh02 commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexRuleAction.java
> +                verifyRule(backend.getQueryFields().keySet(), DetectorMonitorConfig.getRuleIndex(category), new ActionListener<>() {
What if the custom rule is created using the fields not part of the rule alias mapping, but using some additional fields from the Source Index. That still is a valid use case. 
Should we revisit the approach, where the fields in rule could also be present in the source index mapping?

2022-11-01 17:01 UTC, getsaurabh02 commented
Hi @petardz are we on it with the plan as we discussed ?

2022-11-02 03:54 UTC, getsaurabh02 submitted a review, later dismissed

2022-11-03 19:28 UTC, eirsep approved these changes

2022-11-03 19:28 UTC, sbcd90 approved these changes

2022-11-03 19:29 UTC, merged