get all findings as part of findings API enhancement
opensearch-project/security-analytics pull request #803
Opened 2024-01-16 07:47 UTC by riysaxen-amzn

### Description
As part of the commit, the query params detector_id and detectorType have become optional for the `findings/_search` API. As part of the enhancement, the API can now return all the findings for all the detectors.
 
### Issues Resolved
https://github.com/opensearch-project/security-analytics/issues/795
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-01-16 19:41 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java
> +                            "%s is missing", DETECTOR_ID),
why %s?

2024-01-16 20:05 UTC, riysaxen-amzn commented on src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java
> +                            "%s is missing", DETECTOR_ID),
yeah it's not need but I saw that's what we have followed in other methods as well when overriding validate() method. So, I added just to be consistent everywhere. The string will transform to` detector_id is missing`;

2024-01-17 18:45 UTC, jowg-amazon commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
>              // "detector" is nested type, so we have to use nested query
are we still using a nested query here?

2024-01-17 18:45 UTC, jowg-amazon commented on src/test/java/org/opensearch/securityanalytics/findings/FindingIT.java
> +        params.clear();
Is the test unfinished?

2024-01-18 21:00 UTC, eirsep commented
i am not sure this design is correct or maybe i have grossly misunderstood the approach.

Can you add a detailed approach of how findings from detectors of all log types are being fetched?

2024-01-18 21:01 UTC, eirsep requested changes
i am not sure this design is correct or maybe i have grossly misunderstood the approach.

Can you add a detailed approach of how findings from detectors of all log types are being fetched?

2024-01-18 21:45 UTC, riysaxen-amzn commented
> i am not sure this design is correct or maybe i have grossly misunderstood the approach.
> 
> Can you add a detailed approach of how findings from detectors of all log types are being fetched?
So, the idea is first to get all the detectors using `matchAllQuery` [TransportGetFindingsAction.java#L190]. Now to get the findings for all these detectors for all the logTypes, we can search query on index-pattern `.opensearch-sap-*-findings`, this will give us all the findings for all the LogTypes [TransportGetFindingsAction.java#L143]

2024-01-18 21:56 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +    private static SearchRequest getSearchRequest(GetFindingsRequest request) {
can we rename to `getSearchDetectorsRequest`?

2024-01-18 21:57 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +                    QueryBuilders.nestedQuery(
we wont need nested query for match all

2024-01-18 21:57 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +                        actionListener.onFailure(
this is not a failure. plz return empty list in findings response

2024-01-18 21:58 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +    private void transportSearchAction(GetFindingsRequest request, ActionListener<GetFindingsResponse> actionListener, SearchRequest searchRequest) {
rename params and method. name should communicate that method fetches detectors and their correspondign findings

2024-01-18 22:00 UTC, eirsep commented
> i am not sure this design is correct or maybe i have grossly misunderstood the approach.
> 
> Can you add a detailed approach of how findings from detectors of all log types are being fetched?

I don't think there is a good way to fetch the findings for detectors across multiple log types without making changes in alerting

2024-01-18 22:34 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/action/GetFindingsRequest.java
> +                            "%s is missing", DETECTOR_ID),
NIT: let's log without placeholder

2024-01-18 22:57 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +                            request.getLogType() == null ? "*" : request.getLogType(),
how is findings service already handling `"*"`?  I don't see a change in `FIndingsService` class in this PR

2024-01-18 23:28 UTC, eirsep commented
> > i am not sure this design is correct or maybe i have grossly misunderstood the approach.
> > Can you add a detailed approach of how findings from detectors of all log types are being fetched?
> 
> So, the idea is first to get all the detectors using `matchAllQuery` [TransportGetFindingsAction.java#L190]. Now to get the findings for all these detectors for all the logTypes, we can search query on index-pattern `.opensearch-sap-*-findings`, this will give us all the findings for all the LogTypes [TransportGetFindingsAction.java#L143]

Gotcha! thank you. I wasn't aware that we already are searching on the "all finding indices pattern" 

Can you create 2 detectors for different log types and test fetching findings for only one of the log types and verify that behaviour is correct?

2024-01-18 23:34 UTC, riysaxen-amzn commented
> > > i am not sure this design is correct or maybe i have grossly misunderstood the approach.
> > > Can you add a detailed approach of how findings from detectors of all log types are being fetched?
> > 
> > 
> > So, the idea is first to get all the detectors using `matchAllQuery` [TransportGetFindingsAction.java#L190]. Now to get the findings for all these detectors for all the logTypes, we can search query on index-pattern `.opensearch-sap-*-findings`, this will give us all the findings for all the LogTypes [TransportGetFindingsAction.java#L143]
> 
> Gotcha! thank you. I wasn't aware that we already are searching on the "all finding indices pattern"
> 
> Can you create 2 detectors for different log types and test fetching findings for only one of the log types and verify that behaviour is correct?

this test is creating detectors of two different logTypes and verifying the behavior -> https://github.com/opensearch-project/security-analytics/pull/803/files#diff-d37f0c96e5ab58c9a80449652179f36f9696044aa275fc7c7f33ce2677fa6793

2024-02-20 23:47 UTC, engechas approved these changes

2024-02-20 23:47 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/transport/TransportGetFindingsAction.java
> +            getFindingsFromDetectors(request, actionListener, searchRequest);
Minor - the else does the same thing as the if block. I think you can simplify with
```
if (request.getLogType() == null) {
  ...
} else {
  ...
}
```

2024-02-22 07:47 UTC, amsiglan commented
Please make sure we create a PR in the documentation repo to update all the supported params. I see the documentation does not have some existing params too like `startIndex`. Thanks

2024-03-06 17:44 UTC, engechas approved these changes

2024-03-06 17:44 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/resthandler/RestGetFindingsAction.java
> +        }
Minor - could create a private method for this to avoid the duplication with the endTime parsing

2024-03-09 00:16 UTC, jowg-amazon approved these changes
LGTM

2024-03-09 00:17 UTC, jowg-amazon commented
Fix merge conflicts + make sure CI's pass

2024-03-10 23:14 UTC, praveensameneni submitted a review, later dismissed

2024-03-10 23:23 UTC, sbcd90 approved these changes

2024-03-11 05:20 UTC, praveensameneni approved these changes

2024-03-11 05:26 UTC, sbcd90 approved these changes

2024-03-11 05:27 UTC, merged