[BUG] ArrayIndexOutOfBoundsException for inconsistent detector index behavior
opensearch-project/security-analytics pull request #843
Opened 2024-02-08 22:08 UTC by goyamegh

### Description
Fixes the following issues:
1. In case the detector search request returns empty hits, the exception should be gracefully handled and checked before.
2. Case when multiple detectors are present and we are fetching only one detector.
 
### Issues Resolved
#842  
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-09 23:07 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                        // Detectors Index hits count could be more even if we fetch one
just curious why can it >1 ??

2024-02-09 23:13 UTC, eirsep requested changes

2024-02-09 23:13 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                            } catch (ArrayIndexOutOfBoundsException e) {
why are we catching ArrayIndexOutOfBoundsException also if we are adding check on array size???
can we instead add an error log in the IOException catch>

2024-02-14 19:09 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                            } catch (ArrayIndexOutOfBoundsException e) {
Removed.

2024-02-14 19:15 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                        // Detectors Index hits count could be more even if we fetch one
Keeping it >1 in case we remove filters and the number of hits are more than 1.

2024-02-14 19:22 UTC, engechas approved these changes

2024-02-14 19:57 UTC, merged