Return list of cx friendly 4xx errors for indexing custom rules
opensearch-project/security-analytics pull request #862
Opened 2024-02-17 23:05 UTC by goyamegh

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-02-19 02:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
> +            // TODO: Merge the exception to the original list of errors coming from SigmaRule.java and use the same throwing logic
plz resolve TODO

2024-02-19 02:09 UTC, eirsep commented
plz udpate descirption

2024-02-19 02:10 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
> +                log.warn("[CUSTOMER ERROR] Security Analytics error:", e);
why did we change log message level? plz revert

Why did we even change the text and add customer error. unnecessary and confusing?

2024-02-19 02:11 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
> +     * Intended for a curated list of Customer validation exceptions (4xx)
what about 5xx and other HTTP errors??

2024-02-19 06:35 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
> +                log.warn("[CUSTOMER ERROR] Security Analytics error:", e);
This is intentional to be a warning message. All customer related errors need not be part of error logs as they are not system issues. 
Also, this error was modified to convey that this is a client side exception to help with debugging.

Feel free to recommend a more explicit way to differentiate between client-side and server-side errors.

2024-02-19 06:36 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
> +            // TODO: Merge the exception to the original list of errors coming from SigmaRule.java and use the same throwing logic
This will be taken up as a fast-follower, as this requires a more elaborate set of changes.

2024-02-20 00:43 UTC, eirsep requested changes

2024-03-05 18:27 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java
> +    private final List<SigmaError> errorList;
The idea was to ensure backward compatibility. Any customer using this exception should not see exceptions because of our changes. We can discuss this and refactor accordingly as needed.

2024-03-05 18:31 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
> -    public abstract AggregationQueries convertAggregation(AggregationItem aggregation) throws SigmaError;
It was not being thrown by the concrete method, hence redundant and needed cleanup.

2024-03-05 18:46 UTC, sbcd90 commented on src/main/java/org/opensearch/securityanalytics/model/Rule.java
> +    public List<AggregationItem> getAggregationItemsFromRule () throws SigmaErrorList, SigmaConditionError {
can we keep just `SigmaError` or `SigmaErrorList`? it creates confusion to read code with both these 2 exceptions.

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/model/Rule.java
> +        // TODO: Check if there are cx errors from the rule created and throw errors
Minor: could we create GH issues for TODOs and link them? Would help to track this sort of thing

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/rules/backend/QueryBackend.java
> +            // TODO: Merge the exception to the original list of errors coming from SigmaRule.java and use the same throwing logic
Same comment as above about creating/linking an issue

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaError.java
> +    private final String message;
Nice, we should continue slowly cleaning the repo to follow best practices as we encounter this sort of stuff

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java
> +public class SigmaErrorList extends Exception {
Naming nit: maybe CompositeSigmaError. The name `SigmaErrorList` does not imply its an exception imo

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java
> +public class SigmaErrorList extends Exception {
We could also extend SigmaError rather than Exception to avoid changing the checked exceptions throughout the code.

Semi-related - using checked exceptions is a bad practice. Is there a downside of extending a RuntimeException rather than a base Exception? I'm not sure if there are considerations specific to the larger OpenSearch exception handling

2024-04-10 00:50 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/util/SecurityAnalyticsException.java
> +                log.warn("[CUSTOMER ERROR] Security Analytics error:", e);
I'd still advocate for using `error` level over warning for exceptions. We should be able to distinguish user vs server errors with the RestStatus ultimately returned for the API call.

I would also advocate against using prefixes in the exceptions in general. If we do want to keep it, let's change `CUSTOMER` to `USER`.

2024-04-14 01:52 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/model/Rule.java
> +    public List<AggregationItem> getAggregationItemsFromRule () throws SigmaErrorList, SigmaConditionError {
We cannot get away with SigmaError as it is a base class for all Sigma related errors. To avoid confusion, I have renamed the new list object to SigmaCompositeError.

2024-04-15 15:12 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/rules/exceptions/SigmaErrorList.java
> +public class SigmaErrorList extends Exception {
We cannot extend SigmaError, as that would mean that we can have one message string in the exception. This we will append after we have collected all the exceptions in a list, and then finally convert it to SecurityAnalyticsException. 

Further, we can't get away with SigmaError class, as this is a base class for all sigma errors.

Made the semantic changes as suggested.

2024-04-15 18:44 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/Enginecopy.java
> +///*
Removed.

2024-04-15 18:45 UTC, engechas submitted a review, later dismissed

2024-04-15 19:00 UTC, jowg-amazon approved these changes

2024-04-15 19:09 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/model/Rule.java
> +        // TODO: Check if there are cx errors from the rule created and throw errors
+1

2024-04-15 20:26 UTC, engechas approved these changes

2024-04-15 20:28 UTC, jowg-amazon approved these changes

2024-04-15 20:28 UTC, jowg-amazon commented
Should get the CI's passing one round before merging

2024-04-15 22:31 UTC, jowg-amazon approved these changes

2024-04-15 22:39 UTC, engechas approved these changes

2024-04-16 20:38 UTC, merged