Refactor invocation of Action listeners in correlations
opensearch-project/security-analytics pull request #880
Opened 2024-03-04 18:01 UTC by goyamegh

### Description
This PR is intended to fix the hanging tasks observed in _cat/tasks by refactoring the correlation workflow to ensure timely closure of parent action listeners upon successful completion or encountering exceptions, and consolidating exception handling logic into a centralized function. The aim is to optimize task management efficiency and enhance the overall reliability of our system.

This logic has been tested against a high indexing workload ( approx. 1 M docs/ minute) where the issue was observed prominently in a cluster of 3 or more data nodes, and generating findings with the help of a Cloudtrail logs detector running all 32 pre-packaged rules at a frequency of 1 minute. Further, the correlations were generated with the help of a single rule on the same log type for testing, where the findings are generated at a rate of 1~2k per minute.
 
### Issues Resolved
#879
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-05 06:59 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                try {
nit: Try-catch is redundant as we are using ActionListener.wrap() which catches generic Exception

2024-03-05 18:33 UTC, eirsep requested changes

2024-03-05 18:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                    if (hits.getTotalHits().value >= 1 && hits.getHits().length > 0) {
this check looks different in every place. 
Why cant we just iterate hits with a for loop and not do any of these checks

2024-03-05 18:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                        onFailures(new OpenSearchStatusException("detector not found given monitor id", RestStatus.INTERNAL_SERVER_ERROR));
log the monitor id

2024-03-05 18:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                    log.error(new OpenSearchStatusException(bulkResponse.toString(), RestStatus.INTERNAL_SERVER_ERROR));
onfailure()?

2024-03-05 18:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                    String id = searchMetadataResponse.getHits().getHits()[0].getId();
size check on hits array?

2024-03-05 18:33 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                            onFailures(ex);
log exception

2024-03-05 19:54 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                onFailure(new OpenSearchStatusException("Search request timed out", RestStatus.REQUEST_TIMEOUT));
onFailure() will inadvertently throw the exception in finishHim() function in TransportCorrelateFindingsAction.java

2024-03-05 22:37 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                } catch (IOException e) {
onFailure() calls TransportCorrelateFindings.onFailures(), which will make sure that we log this, and that too once in the lifetime of the task.

2024-03-05 22:51 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                            onFailures(ex);
Same comment as before

2024-03-05 22:57 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                    log.error(new OpenSearchStatusException(bulkResponse.toString(), RestStatus.INTERNAL_SERVER_ERROR));
We haven't been following this practice for most bulk requests. But, I checked that the setupCorrelationIndex() is simply indexing two docs, which are later needed as well. Modifying this behavior to fail here itself. @sbcd90 please  verify. This is one of the cases where we observed exceptions on, metadata index not having the right docs.

Rectifying this for other calls too.

2024-03-05 23:08 UTC, eirsep commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                } catch (IOException e) {
we don't need to log at generic failure handling code blocks. we should log in the method so that we are able to communicate where the exception came from or pass a custom error log message to on failure (i would prefer second approach but that would require a lot more change in impl. so was suggesting simple error log. )

2024-03-05 23:56 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                                    String id = searchMetadataResponse.getHits().getHits()[0].getId();
Added.

2024-03-06 00:01 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                    if (hits.getTotalHits().value >= 1 && hits.getHits().length > 0) {
I think the problem is that the usage is different everywhere. This usage only expects a single doc and probably why it was written like this. I can take a quick pass at all usages of getTotalHits() in a follow-up and fix this everywhere to make it consistent. 

Removing the check on total hits entirely.

2024-03-06 00:03 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                    if (response.getResponse().getHits().getTotalHits().value > 0L) {
Corrected.

2024-03-06 00:03 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
> +                onFailure(new OpenSearchStatusException("Search request timed out", RestStatus.REQUEST_TIMEOUT));
It'll happen in finishHim().

2024-03-06 00:04 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/transport/TransportCorrelateFindingAction.java
> +                    AsyncCorrelateFindingAction correlateFindingAction = new AsyncCorrelateFindingAction(task, transformedRequest, actionListener);
Not unintentional. We will use a single onFailures() function across the entire flow. The idea to move it before if condition is to use the same function.

2024-03-06 00:09 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +            log.error("[CORRELATIONS] Exception encountered while searching correlation rule index for finding id {}",
Makes sense. Added in getTimesStampFeature() too.

2024-03-06 00:10 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                try {
Removed.

2024-03-06 01:16 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                    onFailure(e);
Umm, that's not true. Once an exception is raised, the loop will break for this thread. Since we are closing the parent listener, so we should be good.

Anyway, I removed it.

2024-03-06 01:47 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java
> +                onFailure(
Seems like some confusion. The same logic is used twice. No change in logic was done here. 
Check these lines for reference:
1. https://github.com/opensearch-project/security-analytics/blob/main/src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java#L88
2. https://github.com/opensearch-project/security-analytics/blob/main/src/main/java/org/opensearch/securityanalytics/correlation/VectorEmbeddingsEngine.java#L134

2024-03-06 02:46 UTC, goyamegh commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                } catch (IOException e) {
Makes sense. For now, I have logged the following information for now:
1. Exception and stack trace
2. Monitor and finding id of that request
3. Trace should tell us where the exception originated from.

I'm not reverting this for now, as we are missing logging completely at this point. As a long term, I created a git hub issue to take this up: https://github.com/opensearch-project/security-analytics/issues/883

2024-03-06 03:24 UTC, engechas approved these changes

2024-03-06 03:24 UTC, engechas commented on src/main/java/org/opensearch/securityanalytics/correlation/JoinEngine.java
> +                log.error("[CORRELATIONS] Exception encountered while searching correlation rule index for finding id {}",
Minor: we should remove the `[CORRELATIONS] prefix`

2024-03-06 13:10 UTC, eirsep approved these changes

2024-03-06 13:54 UTC, merged