WIP - Feature/add bucket level monitors
opensearch-project/security-analytics pull request #92
Opened 2022-10-31 22:15 UTC by stevanbz

### Description
Enables creation of bucket level monitors based on the aggregation rules.

 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-07 20:06 UTC, stevanbz commented on src/main/java/org/opensearch/securityanalytics/transport/TransportIndexDetectorAction.java
> +            .size(10000);
size(0)

2022-11-07 22:04 UTC, eirsep requested changes

2022-11-07 22:15 UTC, stevanbz commented on src/test/java/org/opensearch/securityanalytics/rules/aggregation/AggregationBackendTests.java
> -        Assert.assertEquals("\"aggs\":{\"result_agg\":{\"terms\":{\"field\":\"fieldB\"}}}", aggQuery);
You can see one line below that I just removed aggs part.

2022-11-07 23:25 UTC, eirsep commented
LGTM 
but plz resolve merge conflicts
\

2022-11-09 18:07 UTC, eirsep approved these changes

2022-11-09 18:08 UTC, sbcd90 approved these changes

2022-11-09 18:13 UTC, merged